-- =============================================================================
-- SmartETRM — Reference/Seed Data: User Management
-- =============================================================================
-- GENERATED FILE — do not hand-edit. Extracted from a live, fully-migrated
-- ETRM_DB (post-V96) via mssql-scripter, one table at a time.
--
-- REFERENCE ONLY — not guaranteed independently runnable in isolation.
-- SmartETRM's Master Data Hub groups are NOT a dependency hierarchy — most
-- groups have FKs pointing at each other in both directions (e.g. Products &
-- Markets needs Finance & Settlement's currency rows; Finance & Settlement's
-- bank_account needs Counterparties & Agreements' counterparty rows). There is
-- no group-by-group load order that satisfies every FK. For an actually-
-- runnable full load, use 01_master_data_seed.sql instead, which loads all
-- 154 tables' data in a verified-safe per-table order. This file exists so you
-- can find/read/diff "what's the seed data for User Management" without wading through
-- the combined file.
--
-- Tables in this file (3): app_user, field_permission_rule, user_role
-- =============================================================================

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


SET IDENTITY_INSERT [dbo].[field_permission_rule] ON 

INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (1, 1, 1, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (2, 1, 2, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (3, 1, 3, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (4, 1, 4, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (5, 1, 5, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (6, 1, 6, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (7, 1, 7, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (8, 1, 8, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (9, 1, 9, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (10, 1, 10, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (11, 1, 11, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (12, 1, 12, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (13, 1, 13, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (14, 1, 14, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (15, 1, 15, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (16, 1, 16, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (17, 1, 17, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (18, 1, 18, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (19, 1, 19, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (20, 1, 20, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (21, 1, 21, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (22, 1, 22, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (23, 1, 23, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (24, 1, 24, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (25, 1, 25, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (26, 1, 26, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (27, 1, 27, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (28, 1, 28, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (29, 1, 29, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (30, 1, 30, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (31, 1, 31, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (32, 1, 32, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (33, 1, 33, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (34, 1, 34, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (35, 1, 35, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (36, 1, 36, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (37, 1, 37, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (38, 1, 38, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (39, 1, 39, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (40, 1, 40, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (41, 1, 41, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (42, 1, 42, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (43, 1, 43, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (44, 1, 44, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (45, 1, 45, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (46, 1, 46, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (47, 1, 47, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (48, 1, 48, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (49, 1, 49, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (50, 1, 50, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (51, 1, 51, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (52, 1, 52, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (53, 1, 53, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (54, 1, 54, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (55, 1, 55, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (56, 1, 56, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (57, 1, 57, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (58, 1, 58, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (59, 1, 59, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (60, 1, 60, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (61, 2, 1, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (62, 2, 2, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (63, 2, 3, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (64, 2, 4, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (65, 2, 5, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (66, 2, 6, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (67, 2, 7, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (68, 2, 8, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (69, 2, 9, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (70, 2, 10, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (71, 2, 11, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (72, 2, 12, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (73, 2, 13, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (74, 2, 14, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (75, 2, 15, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (76, 2, 16, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (77, 2, 17, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (78, 2, 18, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (79, 2, 19, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (80, 2, 20, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (81, 2, 21, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (82, 2, 22, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (83, 2, 23, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (84, 2, 24, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (85, 2, 25, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (86, 2, 26, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (87, 2, 27, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (88, 2, 28, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (89, 2, 29, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (90, 2, 30, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (91, 2, 31, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (92, 2, 32, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (93, 2, 33, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (94, 2, 34, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (95, 2, 35, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (96, 2, 36, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (97, 2, 37, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (98, 2, 38, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (99, 2, 39, N'HIDDEN')
GO
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (100, 2, 40, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (101, 2, 41, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (102, 2, 42, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (103, 2, 43, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (104, 2, 44, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (105, 2, 45, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (106, 2, 46, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (107, 2, 47, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (108, 2, 48, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (109, 2, 49, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (110, 2, 50, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (111, 2, 51, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (112, 2, 52, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (113, 2, 53, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (114, 2, 54, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (115, 2, 55, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (116, 2, 56, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (117, 2, 57, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (118, 2, 58, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (119, 2, 59, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (120, 2, 60, N'HIDDEN')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (121, 3, 1, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (122, 3, 2, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (123, 3, 3, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (124, 3, 4, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (125, 3, 5, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (126, 3, 6, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (127, 3, 7, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (128, 3, 8, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (129, 3, 9, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (130, 3, 10, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (131, 3, 11, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (132, 3, 12, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (133, 3, 13, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (134, 3, 14, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (135, 3, 15, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (136, 3, 16, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (137, 3, 17, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (138, 3, 18, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (139, 3, 19, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (140, 3, 20, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (141, 3, 21, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (142, 3, 22, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (143, 3, 23, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (144, 3, 24, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (145, 3, 25, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (146, 3, 26, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (147, 3, 27, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (148, 3, 28, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (149, 3, 29, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (150, 3, 30, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (151, 3, 31, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (152, 3, 32, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (153, 3, 33, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (154, 3, 34, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (155, 3, 35, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (156, 3, 36, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (157, 3, 37, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (158, 3, 38, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (159, 3, 39, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (160, 3, 40, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (161, 3, 41, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (162, 3, 42, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (163, 3, 43, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (164, 3, 44, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (165, 3, 45, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (166, 3, 46, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (167, 3, 47, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (168, 3, 48, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (169, 3, 49, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (170, 3, 50, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (171, 3, 51, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (172, 3, 52, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (173, 3, 53, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (174, 3, 54, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (175, 3, 55, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (176, 3, 56, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (177, 3, 57, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (178, 3, 58, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (179, 3, 59, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (180, 3, 60, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (181, 4, 1, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (182, 4, 2, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (183, 4, 3, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (184, 4, 4, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (185, 4, 5, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (186, 4, 6, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (187, 4, 7, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (188, 4, 8, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (189, 4, 9, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (190, 4, 10, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (191, 4, 11, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (192, 4, 12, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (193, 4, 13, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (194, 4, 14, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (195, 4, 15, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (196, 4, 16, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (197, 4, 17, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (198, 4, 18, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (199, 4, 19, N'VIEW')
GO
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (200, 4, 20, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (201, 4, 21, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (202, 4, 22, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (203, 4, 23, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (204, 4, 24, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (205, 4, 25, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (206, 4, 26, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (207, 4, 27, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (208, 4, 28, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (209, 4, 29, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (210, 4, 30, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (211, 4, 31, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (212, 4, 32, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (213, 4, 33, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (214, 4, 34, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (215, 4, 35, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (216, 4, 36, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (217, 4, 37, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (218, 4, 38, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (219, 4, 39, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (220, 4, 40, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (221, 4, 41, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (222, 4, 42, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (223, 4, 43, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (224, 4, 44, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (225, 4, 45, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (226, 4, 46, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (227, 4, 47, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (228, 4, 48, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (229, 4, 49, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (230, 4, 50, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (231, 4, 51, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (232, 4, 52, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (233, 4, 53, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (234, 4, 54, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (235, 4, 55, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (236, 4, 56, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (237, 4, 57, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (238, 4, 58, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (239, 4, 59, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (240, 4, 60, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (241, 5, 1, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (242, 5, 2, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (243, 5, 3, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (244, 5, 4, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (245, 5, 5, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (246, 5, 6, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (247, 5, 7, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (248, 5, 8, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (249, 5, 9, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (250, 5, 10, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (251, 5, 11, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (252, 5, 12, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (253, 5, 13, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (254, 5, 14, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (255, 5, 15, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (256, 5, 16, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (257, 5, 17, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (258, 5, 18, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (259, 5, 19, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (260, 5, 20, N'VIEW')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (261, 5, 21, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (262, 5, 22, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (263, 5, 23, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (264, 5, 24, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (265, 5, 25, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (266, 5, 26, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (267, 5, 27, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (268, 5, 28, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (269, 5, 29, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (270, 5, 30, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (271, 5, 31, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (272, 5, 32, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (273, 5, 33, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (274, 5, 34, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (275, 5, 35, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (276, 5, 36, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (277, 5, 37, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (278, 5, 38, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (279, 5, 39, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (280, 5, 40, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (281, 5, 41, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (282, 5, 42, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (283, 5, 43, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (284, 5, 44, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (285, 5, 45, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (286, 5, 46, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (287, 5, 47, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (288, 5, 48, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (289, 5, 49, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (290, 5, 50, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (291, 5, 51, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (292, 5, 52, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (293, 5, 53, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (294, 5, 54, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (295, 5, 55, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (296, 5, 56, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (297, 5, 57, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (298, 5, 58, N'EDIT')
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (299, 5, 59, N'EDIT')
GO
INSERT [dbo].[field_permission_rule] ([rule_id], [profile_id], [field_id], [field_permission]) VALUES (300, 5, 60, N'EDIT')
SET IDENTITY_INSERT [dbo].[field_permission_rule] OFF

SET IDENTITY_INSERT [dbo].[user_role] ON 

INSERT [dbo].[user_role] ([role_id], [role_code], [role_name], [description], [role_type], [status], [rejection_reason], [is_active], [created_at], [created_by], [submitted_at], [approved_by], [approved_at], [updated_at], [updated_by]) VALUES (1, N'ADMIN', N'System Administrator', N'Full access to all modules including administration', N'SYSTEM', N'APPROVED', NULL, 1, CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), N'SYSTEM', NULL, N'SYSTEM', CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), N'SYSTEM')
INSERT [dbo].[user_role] ([role_id], [role_code], [role_name], [description], [role_type], [status], [rejection_reason], [is_active], [created_at], [created_by], [submitted_at], [approved_by], [approved_at], [updated_at], [updated_by]) VALUES (2, N'TRADER', N'Trader', N'Create and manage trades; view counterparties and master data', N'SYSTEM', N'APPROVED', NULL, 1, CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), N'SYSTEM', NULL, N'SYSTEM', CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), N'SYSTEM')
INSERT [dbo].[user_role] ([role_id], [role_code], [role_name], [description], [role_type], [status], [rejection_reason], [is_active], [created_at], [created_by], [submitted_at], [approved_by], [approved_at], [updated_at], [updated_by]) VALUES (3, N'RISK_MANAGER', N'Risk Manager', N'View and approve trades; view positions and P&L', N'SYSTEM', N'APPROVED', NULL, 1, CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), N'SYSTEM', NULL, N'SYSTEM', CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), N'SYSTEM')
INSERT [dbo].[user_role] ([role_id], [role_code], [role_name], [description], [role_type], [status], [rejection_reason], [is_active], [created_at], [created_by], [submitted_at], [approved_by], [approved_at], [updated_at], [updated_by]) VALUES (4, N'OPERATIONS', N'Operations', N'Full counterparty and master data management; view trades', N'SYSTEM', N'APPROVED', NULL, 1, CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), N'SYSTEM', NULL, N'SYSTEM', CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), N'SYSTEM')
INSERT [dbo].[user_role] ([role_id], [role_code], [role_name], [description], [role_type], [status], [rejection_reason], [is_active], [created_at], [created_by], [submitted_at], [approved_by], [approved_at], [updated_at], [updated_by]) VALUES (5, N'COMPLIANCE', N'Compliance', N'View and manage KYC/counterparty data; view trades', N'SYSTEM', N'APPROVED', NULL, 1, CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), N'SYSTEM', NULL, N'SYSTEM', CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), N'SYSTEM')
INSERT [dbo].[user_role] ([role_id], [role_code], [role_name], [description], [role_type], [status], [rejection_reason], [is_active], [created_at], [created_by], [submitted_at], [approved_by], [approved_at], [updated_at], [updated_by]) VALUES (6, N'VIEWER', N'Read-Only Viewer', N'Read-only access to all non-admin modules', N'SYSTEM', N'APPROVED', NULL, 1, CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), N'SYSTEM', NULL, N'SYSTEM', CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), CAST(N'2026-07-12T11:19:45.6680422' AS DateTime2), N'SYSTEM')
SET IDENTITY_INSERT [dbo].[user_role] OFF

