-- =============================================================================
-- SmartETRM — Reference/Seed Data: Counterparties & Agreements
-- =============================================================================
-- GENERATED FILE — do not hand-edit. Extracted from a live, fully-migrated
-- ETRM_DB (post-V96) via mssql-scripter, one table at a time.
--
-- REFERENCE ONLY — not guaranteed independently runnable in isolation.
-- SmartETRM's Master Data Hub groups are NOT a dependency hierarchy — most
-- groups have FKs pointing at each other in both directions (e.g. Products &
-- Markets needs Finance & Settlement's currency rows; Finance & Settlement's
-- bank_account needs Counterparties & Agreements' counterparty rows). There is
-- no group-by-group load order that satisfies every FK. For an actually-
-- runnable full load, use 01_master_data_seed.sql instead, which loads all
-- 154 tables' data in a verified-safe per-table order. This file exists so you
-- can find/read/diff "what's the seed data for Counterparties & Agreements" without wading through
-- the combined file.
--
-- Tables in this file (13): address_type, bank_account_type, counterparty_type, credit_rating, credit_term, kyc_status, counterparty, cp_gtc_agreement, intercompany_transfer_rule, netting_agreement_type, netting_agreement, cp_commercial_terms, broker
-- =============================================================================

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

SET IDENTITY_INSERT [dbo].[address_type] ON 

INSERT [dbo].[address_type] ([address_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (1, N'REGISTERED', N'Registered', N'Official registered office address', 1, 1, CAST(N'2026-07-12T11:19:45.1977420' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1977420' AS DateTime2), N'SYSTEM')
INSERT [dbo].[address_type] ([address_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (2, N'TRADING', N'Trading', N'Principal place of business for trading operations', 2, 1, CAST(N'2026-07-12T11:19:45.1977420' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1977420' AS DateTime2), N'SYSTEM')
INSERT [dbo].[address_type] ([address_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (3, N'BILLING', N'Billing', N'Invoice and payment correspondence address', 3, 1, CAST(N'2026-07-12T11:19:45.1977420' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1977420' AS DateTime2), N'SYSTEM')
INSERT [dbo].[address_type] ([address_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (4, N'SHIPPING', N'Shipping', N'Shipping or despatch point address', 4, 1, CAST(N'2026-07-12T11:19:45.1977420' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1977420' AS DateTime2), N'SYSTEM')
INSERT [dbo].[address_type] ([address_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (5, N'DELIVERY', N'Delivery', N'Physical delivery or receiving address', 5, 1, CAST(N'2026-07-12T11:19:45.1977420' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1977420' AS DateTime2), N'SYSTEM')
INSERT [dbo].[address_type] ([address_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (6, N'OTHER', N'Other', N'Address purpose does not fit standard classifications', 6, 1, CAST(N'2026-07-12T11:19:45.1977420' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1977420' AS DateTime2), N'SYSTEM')
SET IDENTITY_INSERT [dbo].[address_type] OFF

SET IDENTITY_INSERT [dbo].[bank_account_type] ON 

INSERT [dbo].[bank_account_type] ([bank_account_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (1, N'SETTLEMENT', N'Settlement', N'Primary account for trade settlement payments', 1, 1, CAST(N'2026-07-12T11:19:45.2025537' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.2025537' AS DateTime2), N'SYSTEM')
INSERT [dbo].[bank_account_type] ([bank_account_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (2, N'COLLATERAL', N'Collateral', N'Designated account for posting or receiving collateral', 2, 1, CAST(N'2026-07-12T11:19:45.2025537' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.2025537' AS DateTime2), N'SYSTEM')
INSERT [dbo].[bank_account_type] ([bank_account_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (3, N'FEE', N'Fee', N'Account for brokerage and service fee payments', 3, 1, CAST(N'2026-07-12T11:19:45.2025537' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.2025537' AS DateTime2), N'SYSTEM')
INSERT [dbo].[bank_account_type] ([bank_account_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (4, N'MARGIN', N'Margin', N'Exchange or CCP margin account', 4, 1, CAST(N'2026-07-12T11:19:45.2025537' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.2025537' AS DateTime2), N'SYSTEM')
INSERT [dbo].[bank_account_type] ([bank_account_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (5, N'GENERAL', N'General', N'General-purpose operating account', 5, 1, CAST(N'2026-07-12T11:19:45.2025537' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.2025537' AS DateTime2), N'SYSTEM')
INSERT [dbo].[bank_account_type] ([bank_account_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (6, N'ESCROW', N'Escrow', N'Third-party held escrow account', 6, 1, CAST(N'2026-07-12T11:19:45.2025537' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.2025537' AS DateTime2), N'SYSTEM')
SET IDENTITY_INSERT [dbo].[bank_account_type] OFF

SET IDENTITY_INSERT [dbo].[counterparty_type] ON 

INSERT [dbo].[counterparty_type] ([counterparty_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (1, N'PRODUCER', N'Producer', N'Commodity producer — upstream, extraction or generation', 1, 1, CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM')
INSERT [dbo].[counterparty_type] ([counterparty_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (2, N'CONSUMER', N'Consumer', N'End consumer — industrial, utility, or retail buyer', 2, 1, CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM')
INSERT [dbo].[counterparty_type] ([counterparty_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (3, N'TRADER', N'Trader', N'Physical or financial trading company', 3, 1, CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM')
INSERT [dbo].[counterparty_type] ([counterparty_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (4, N'BANK', N'Bank', N'Financial institution — credit, clearing, structured finance', 4, 1, CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM')
INSERT [dbo].[counterparty_type] ([counterparty_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (5, N'BROKER', N'Broker (deprecated)', N'Intermediary executing on behalf of principals', 99, 0, CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM')
INSERT [dbo].[counterparty_type] ([counterparty_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (6, N'EXCHANGE', N'Exchange', N'Regulated trading venue (ICE, NYMEX, LME, EEX)', 8, 1, CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM')
INSERT [dbo].[counterparty_type] ([counterparty_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (7, N'INTERCOMPANY', N'Intercompany', N'Intra-group entity — same legal group as a legal_entity', 9, 1, CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM')
INSERT [dbo].[counterparty_type] ([counterparty_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (8, N'UTILITY', N'Utility', N'Energy utility — power generator or gas distributor', 10, 1, CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM')
INSERT [dbo].[counterparty_type] ([counterparty_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (9, N'OTHER', N'Other', N'Does not fit any standard counterparty classification', 11, 1, CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1686390' AS DateTime2), N'SYSTEM')
INSERT [dbo].[counterparty_type] ([counterparty_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (10, N'FCM', N'FCM — Clearing Broker', N'Futures Commission Merchant: the legal counterparty on your exchange-listed trades. Executes and clears futures/options, holds margin accounts on ICE/NYMEX/LME/EEX. Examples: Marex, Macquarie, StoneX, bank clearing desks.', 5, 1, CAST(N'2026-07-12T11:19:46.7306268' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:46.7306268' AS DateTime2), N'SYSTEM')
INSERT [dbo].[counterparty_type] ([counterparty_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (11, N'PRIME', N'Prime Broker', N'Central counterparty across all venues under one ISDA/GMRA umbrella. Credit intermediation, cross-product netting, portfolio margining. Always the legal counterparty on every trade booked through them.', 6, 1, CAST(N'2026-07-12T11:19:46.7357210' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:46.7357210' AS DateTime2), N'SYSTEM')
SET IDENTITY_INSERT [dbo].[counterparty_type] OFF

SET IDENTITY_INSERT [dbo].[credit_rating] ON 

INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (1, N'SP', N'AAA', 1, N'INVESTMENT_GRADE', N'Highest quality', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (2, N'SP', N'AA+', 2, N'INVESTMENT_GRADE', N'Very high quality', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (3, N'SP', N'AA', 3, N'INVESTMENT_GRADE', N'Very high quality', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (4, N'SP', N'AA-', 4, N'INVESTMENT_GRADE', N'Very high quality', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (5, N'SP', N'A+', 5, N'INVESTMENT_GRADE', N'High quality', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (6, N'SP', N'A', 6, N'INVESTMENT_GRADE', N'High quality', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (7, N'SP', N'A-', 7, N'INVESTMENT_GRADE', N'High quality', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (8, N'SP', N'BBB+', 8, N'INVESTMENT_GRADE', N'Good quality', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (9, N'SP', N'BBB', 9, N'INVESTMENT_GRADE', N'Good quality', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (10, N'SP', N'BBB-', 10, N'INVESTMENT_GRADE', N'Lowest investment grade', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (11, N'SP', N'BB+', 11, N'SPECULATIVE', N'Speculative', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (12, N'SP', N'BB', 12, N'SPECULATIVE', N'Speculative', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (13, N'SP', N'BB-', 13, N'SPECULATIVE', N'Speculative', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (14, N'SP', N'B+', 14, N'SPECULATIVE', N'Highly speculative', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (15, N'SP', N'B', 15, N'SPECULATIVE', N'Highly speculative', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (16, N'SP', N'B-', 16, N'SPECULATIVE', N'Highly speculative', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (17, N'SP', N'CCC', 17, N'SPECULATIVE', N'Substantial risk', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (18, N'SP', N'CC', 18, N'SPECULATIVE', N'Near default', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (19, N'SP', N'D', 20, N'DEFAULT', N'Default', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (20, N'INTERNAL', N'APPROVED', 1, N'INVESTMENT_GRADE', N'Internally approved', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (21, N'INTERNAL', N'WATCH', 10, N'SPECULATIVE', N'On internal credit watch', 1)
INSERT [dbo].[credit_rating] ([credit_rating_id], [agency], [rating], [numeric_score], [risk_category], [description], [is_active]) VALUES (22, N'INTERNAL', N'RESTRICTED', 20, N'DEFAULT', N'Restricted — no new trades', 1)
SET IDENTITY_INSERT [dbo].[credit_rating] OFF

SET IDENTITY_INSERT [dbo].[credit_term] ON 

INSERT [dbo].[credit_term] ([credit_term_id], [term_code], [term_name], [credit_period_days], [collateral_type], [margin_call_threshold], [netting_eligible], [requires_isda], [description], [is_active], [margin_call_currency_id]) VALUES (9, N'NET_7', N'Net 7 Days', 7, N'NONE', NULL, 0, 0, N'Open unsecured credit, due 7 days from invoice.', 1, 1)
INSERT [dbo].[credit_term] ([credit_term_id], [term_code], [term_name], [credit_period_days], [collateral_type], [margin_call_threshold], [netting_eligible], [requires_isda], [description], [is_active], [margin_call_currency_id]) VALUES (10, N'NET_14', N'Net 14 Days', 14, N'NONE', NULL, 0, 0, N'Open unsecured credit, due 14 days from invoice.', 1, 1)
INSERT [dbo].[credit_term] ([credit_term_id], [term_code], [term_name], [credit_period_days], [collateral_type], [margin_call_threshold], [netting_eligible], [requires_isda], [description], [is_active], [margin_call_currency_id]) VALUES (11, N'NET_30', N'Net 30 Days', 30, N'NONE', NULL, 0, 0, N'Open unsecured credit, due 30 days from invoice.', 1, 1)
INSERT [dbo].[credit_term] ([credit_term_id], [term_code], [term_name], [credit_period_days], [collateral_type], [margin_call_threshold], [netting_eligible], [requires_isda], [description], [is_active], [margin_call_currency_id]) VALUES (12, N'NET_45', N'Net 45 Days', 45, N'NONE', NULL, 0, 0, N'Open unsecured credit, due 45 days from invoice.', 1, 1)
INSERT [dbo].[credit_term] ([credit_term_id], [term_code], [term_name], [credit_period_days], [collateral_type], [margin_call_threshold], [netting_eligible], [requires_isda], [description], [is_active], [margin_call_currency_id]) VALUES (13, N'NET_60', N'Net 60 Days', 60, N'NONE', NULL, 0, 0, N'Open unsecured credit, due 60 days from invoice.', 1, 1)
INSERT [dbo].[credit_term] ([credit_term_id], [term_code], [term_name], [credit_period_days], [collateral_type], [margin_call_threshold], [netting_eligible], [requires_isda], [description], [is_active], [margin_call_currency_id]) VALUES (14, N'NET_90', N'Net 90 Days', 90, N'NONE', NULL, 0, 0, N'Open unsecured credit, due 90 days from invoice.', 1, 1)
INSERT [dbo].[credit_term] ([credit_term_id], [term_code], [term_name], [credit_period_days], [collateral_type], [margin_call_threshold], [netting_eligible], [requires_isda], [description], [is_active], [margin_call_currency_id]) VALUES (15, N'PREPAY', N'Prepaid — No Credit', 0, N'CASH', NULL, 0, 0, N'Full payment required before delivery/execution — no open credit exposure.', 1, 1)
INSERT [dbo].[credit_term] ([credit_term_id], [term_code], [term_name], [credit_period_days], [collateral_type], [margin_call_threshold], [netting_eligible], [requires_isda], [description], [is_active], [margin_call_currency_id]) VALUES (16, N'CASH_ON_DELIVERY', N'Cash on Delivery', 0, N'CASH', NULL, 0, 0, N'Payment due concurrent with delivery — no open credit exposure.', 1, 1)
INSERT [dbo].[credit_term] ([credit_term_id], [term_code], [term_name], [credit_period_days], [collateral_type], [margin_call_threshold], [netting_eligible], [requires_isda], [description], [is_active], [margin_call_currency_id]) VALUES (17, N'LC_BACKED', N'Letter of Credit Backed', 0, N'LETTER_OF_CREDIT', NULL, 0, 0, N'Fully secured by a standby or documentary LC — no open credit exposure.', 1, 1)
INSERT [dbo].[credit_term] ([credit_term_id], [term_code], [term_name], [credit_period_days], [collateral_type], [margin_call_threshold], [netting_eligible], [requires_isda], [description], [is_active], [margin_call_currency_id]) VALUES (18, N'PARENT_GUAR', N'Parent Guarantee Backed', 30, N'PARENT_GUARANTEE', NULL, 0, 0, N'Credit period extended on the strength of a parent company guarantee.', 1, 1)
INSERT [dbo].[credit_term] ([credit_term_id], [term_code], [term_name], [credit_period_days], [collateral_type], [margin_call_threshold], [netting_eligible], [requires_isda], [description], [is_active], [margin_call_currency_id]) VALUES (19, N'ISDA_CSA_STD', N'ISDA/CSA Standard Margined', 2, N'CASH', CAST(250000.00 AS Decimal(18, 2)), 1, 1, N'Daily-margined facility under an ISDA Master Agreement + CSA.', 1, 1)
SET IDENTITY_INSERT [dbo].[credit_term] OFF

SET IDENTITY_INSERT [dbo].[kyc_status] ON 

INSERT [dbo].[kyc_status] ([kyc_status_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (1, N'PENDING', N'Pending', N'KYC documentation submitted, awaiting review', 1, 1, CAST(N'2026-07-12T11:19:45.1785221' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1785221' AS DateTime2), N'SYSTEM')
INSERT [dbo].[kyc_status] ([kyc_status_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (2, N'APPROVED', N'Approved', N'KYC complete and approved — counterparty tradeable', 2, 1, CAST(N'2026-07-12T11:19:45.1785221' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1785221' AS DateTime2), N'SYSTEM')
INSERT [dbo].[kyc_status] ([kyc_status_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (3, N'REVIEW', N'Review', N'KYC under periodic review — trading may be restricted', 3, 1, CAST(N'2026-07-12T11:19:45.1785221' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1785221' AS DateTime2), N'SYSTEM')
INSERT [dbo].[kyc_status] ([kyc_status_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (4, N'SUSPENDED', N'Suspended', N'KYC suspended — trading halted pending investigation', 4, 1, CAST(N'2026-07-12T11:19:45.1785221' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1785221' AS DateTime2), N'SYSTEM')
INSERT [dbo].[kyc_status] ([kyc_status_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (5, N'REJECTED', N'Rejected', N'KYC failed — counterparty cannot be onboarded', 5, 1, CAST(N'2026-07-12T11:19:45.1785221' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.1785221' AS DateTime2), N'SYSTEM')
SET IDENTITY_INSERT [dbo].[kyc_status] OFF




SET IDENTITY_INSERT [dbo].[netting_agreement_type] ON 

INSERT [dbo].[netting_agreement_type] ([netting_agreement_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (1, N'ISDA_2002', N'ISDA 2002 MA', N'International Swaps & Derivatives Assoc. 2002 Master Agreement', 1, 1, CAST(N'2026-07-12T11:19:45.2485710' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.2485710' AS DateTime2), N'SYSTEM')
INSERT [dbo].[netting_agreement_type] ([netting_agreement_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (2, N'ISDA_1992', N'ISDA 1992 MA', N'ISDA 1992 Master Agreement (predecessor to 2002 MA)', 2, 1, CAST(N'2026-07-12T11:19:45.2485710' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.2485710' AS DateTime2), N'SYSTEM')
INSERT [dbo].[netting_agreement_type] ([netting_agreement_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (3, N'EFET', N'EFET GTMA', N'European Federation of Energy Traders General Agreement', 3, 1, CAST(N'2026-07-12T11:19:45.2485710' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.2485710' AS DateTime2), N'SYSTEM')
INSERT [dbo].[netting_agreement_type] ([netting_agreement_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (4, N'GTMA', N'GTMA', N'Gas & Electricity Markets Trading Master Agreement', 4, 1, CAST(N'2026-07-12T11:19:45.2485710' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.2485710' AS DateTime2), N'SYSTEM')
INSERT [dbo].[netting_agreement_type] ([netting_agreement_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (5, N'NAESB', N'NAESB', N'North American Energy Standards Board Base Contract', 5, 1, CAST(N'2026-07-12T11:19:45.2485710' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.2485710' AS DateTime2), N'SYSTEM')
INSERT [dbo].[netting_agreement_type] ([netting_agreement_type_id], [type_code], [type_name], [description], [sort_order], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (6, N'OTHER', N'Other', N'Bespoke or non-standard netting framework', 6, 1, CAST(N'2026-07-12T11:19:45.2485710' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:45.2485710' AS DateTime2), N'SYSTEM')
SET IDENTITY_INSERT [dbo].[netting_agreement_type] OFF



SET IDENTITY_INSERT [dbo].[broker] ON 

INSERT [dbo].[broker] ([broker_id], [broker_code], [broker_name], [is_active], [created_at], [broker_type], [description], [contact_name], [contact_email], [contact_phone], [website], [legal_doc_id], [commission_notes], [commodity_type], [commission_uom_id], [country_id]) VALUES (1, N'ICAP', N'ICAP Energy', 1, CAST(N'2026-07-12T11:19:46.6600000' AS DateTime2), N'VOICE', N'Leading OTC voice IDB for crude oil, products, and natural gas. FCA authorised. North Sea, Mediterranean, and US physical markets. Standard OBA in place.', NULL, N'trading@icap.com', NULL, N'https://www.icap.com', N'OBA-ICAP-2024-001', N'Standard rate $0.02/BBL crude oil, $0.015/BBL products. Vol rebate >1M BBL/month.', N'OIL', 1, 1)
INSERT [dbo].[broker] ([broker_id], [broker_code], [broker_name], [is_active], [created_at], [broker_type], [description], [contact_name], [contact_email], [contact_phone], [website], [legal_doc_id], [commission_notes], [commodity_type], [commission_uom_id], [country_id]) VALUES (2, N'GFI', N'GFI Group Commodities', 1, CAST(N'2026-07-12T11:19:46.6600000' AS DateTime2), N'HYBRID', N'OTC IDB for power, gas, and emissions. European gas and power — TTF, NBP, EEX. Voice desk alongside Trayport-connected electronic platform.', NULL, N'commodities@gfi.com', NULL, N'https://www.gfigroup.com', N'OBA-GFI-2023-007', N'$0.015/MWH gas, EUR 0.01/MWH power. Emissions: 0.02 EUR/EUA.', NULL, 4, 2)
INSERT [dbo].[broker] ([broker_id], [broker_code], [broker_name], [is_active], [created_at], [broker_type], [description], [contact_name], [contact_email], [contact_phone], [website], [legal_doc_id], [commission_notes], [commodity_type], [commission_uom_id], [country_id]) VALUES (3, N'BGC', N'BGC Partners Energy', 1, CAST(N'2026-07-12T11:19:46.6600000' AS DateTime2), N'VOICE', N'OTC voice IDB for crude oil, refined products, and freight. Tanker freight and Mediterranean crude. FCA/CFTC dual regulated.', NULL, N'energy@bgcpartners.com', NULL, N'https://www.bgcpartners.com', N'OBA-BGC-2024-003', N'$0.03/BBL crude, $0.025/BBL distillates. Freight: $2,500 flat per VLCC voyage.', NULL, 1, 1)
INSERT [dbo].[broker] ([broker_id], [broker_code], [broker_name], [is_active], [created_at], [broker_type], [description], [contact_name], [contact_email], [contact_phone], [website], [legal_doc_id], [commission_notes], [commodity_type], [commission_uom_id], [country_id]) VALUES (4, N'TRADITION', N'Tradition Financial Services', 1, CAST(N'2026-07-12T11:19:46.6600000' AS DateTime2), N'VOICE', N'Voice IDB for tanker freight, crude oil, and LNG. Primary contact for TD3C, TC2, and Baltic Dirty Tanker routes. BIMCO proforma preferred.', NULL, N'energy@tradition.com', NULL, N'https://www.tradition.com', N'OBA-TRAD-2023-012', N'Freight: $2,000–$3,500 per voyage by route/size. LNG: $1,500 per cargo.', N'GAS', NULL, 1)
INSERT [dbo].[broker] ([broker_id], [broker_code], [broker_name], [is_active], [created_at], [broker_type], [description], [contact_name], [contact_email], [contact_phone], [website], [legal_doc_id], [commission_notes], [commodity_type], [commission_uom_id], [country_id]) VALUES (5, N'TP-ICAP', N'TP ICAP Global Broking', 1, CAST(N'2026-07-12T11:19:46.6600000' AS DateTime2), N'HYBRID', N'Largest OTC IDB globally. All energy commodities. Parameta Solutions electronic platform alongside traditional voice brokerage across oil, gas, power, and freight.', NULL, N'energy@tpicap.com', NULL, N'https://www.tpicap.com', N'OBA-TPICAP-2024-002', N'Gas: EUR 0.01/MWH. Power: EUR 0.008/MWH electronic, EUR 0.012/MWH voice.', NULL, 4, 1)
INSERT [dbo].[broker] ([broker_id], [broker_code], [broker_name], [is_active], [created_at], [broker_type], [description], [contact_name], [contact_email], [contact_phone], [website], [legal_doc_id], [commission_notes], [commodity_type], [commission_uom_id], [country_id]) VALUES (6, N'TULLETT', N'Tullett Prebon', 1, CAST(N'2026-07-12T11:19:46.6600000' AS DateTime2), N'VOICE', N'Voice IDB for metals and base commodities. LME copper, aluminium, zinc, and nickel. Retained brand within TP ICAP group for metals brokerage.', NULL, N'metals@tullettprebon.com', NULL, N'https://www.tullettprebon.com', N'OBA-TULLETT-2023-008', N'LME base metals: $1.50/MT. Precious metals: 0.02% of notional.', NULL, 3, 1)
INSERT [dbo].[broker] ([broker_id], [broker_code], [broker_name], [is_active], [created_at], [broker_type], [description], [contact_name], [contact_email], [contact_phone], [website], [legal_doc_id], [commission_notes], [commodity_type], [commission_uom_id], [country_id]) VALUES (7, N'SPARK', N'Spark Commodities', 1, CAST(N'2026-07-12T11:19:46.7200000' AS DateTime2), N'ELECTRONIC', N'Pure electronic LNG and freight platform. Digital order book for JKM spot, FOB Atlantic, and Pacific freight. Fully algorithmic matching — no voice desk.', NULL, N'trading@sparkcommodities.com', NULL, N'https://www.sparkcommodities.com', N'SPARK-AGREE-2024-001', N'LNG: $0.50/MMBTU per cargo. Freight: 0.10% of worldscale notional.', NULL, NULL, 8)
SET IDENTITY_INSERT [dbo].[broker] OFF

