-- =============================================================================
-- SmartETRM — Reference/Seed Data: Freight & Shipping
-- =============================================================================
-- GENERATED FILE — do not hand-edit. Extracted from a live, fully-migrated
-- ETRM_DB (post-V96) via mssql-scripter, one table at a time.
--
-- REFERENCE ONLY — not guaranteed independently runnable in isolation.
-- SmartETRM's Master Data Hub groups are NOT a dependency hierarchy — most
-- groups have FKs pointing at each other in both directions (e.g. Products &
-- Markets needs Finance & Settlement's currency rows; Finance & Settlement's
-- bank_account needs Counterparties & Agreements' counterparty rows). There is
-- no group-by-group load order that satisfies every FK. For an actually-
-- runnable full load, use 01_master_data_seed.sql instead, which loads all
-- 154 tables' data in a verified-safe per-table order. This file exists so you
-- can find/read/diff "what's the seed data for Freight & Shipping" without wading through
-- the combined file.
--
-- Tables in this file (8): charter_party_type, demurrage_dispatch_rate, laytime_exception_type, laytime_term_template, freight_rate_index, lng_terminal_detail, transport_route, lng_boil_off_rule
-- =============================================================================

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

SET IDENTITY_INSERT [dbo].[charter_party_type] ON 

INSERT [dbo].[charter_party_type] ([charter_party_type_id], [type_code], [type_name], [rate_basis], [duration_basis], [standard_form_reference], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (1, N'VOYAGE', N'Voyage Charter', N'PER_TONNE', N'SINGLE_VOYAGE', N'ASBATANKVOY / GENCON / LNGVOY (BIMCO)', N'Single voyage, freight per tonne or lumpsum, owner bears voyage costs and risk.', 1, CAST(N'2026-07-12T11:19:44.3988082' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.3988082' AS DateTime2), N'SYSTEM')
INSERT [dbo].[charter_party_type] ([charter_party_type_id], [type_code], [type_name], [rate_basis], [duration_basis], [standard_form_reference], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (2, N'TC', N'Time Charter', N'PER_DAY', N'TIME_PERIOD', N'SHELLTIME4 / NYPE', N'Vessel hired for a fixed period; charterer directs voyages and pays bunkers/port costs; owner paid daily hire.', 1, CAST(N'2026-07-12T11:19:44.3988082' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.3988082' AS DateTime2), N'SYSTEM')
INSERT [dbo].[charter_party_type] ([charter_party_type_id], [type_code], [type_name], [rate_basis], [duration_basis], [standard_form_reference], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (3, N'BAREBOAT', N'Bareboat / Demise Charter', N'PER_DAY', N'BAREBOAT_PERIOD', N'BARECON', N'Charterer takes full operational control including crewing; owner provides vessel only.', 1, CAST(N'2026-07-12T11:19:44.3988082' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.3988082' AS DateTime2), N'SYSTEM')
INSERT [dbo].[charter_party_type] ([charter_party_type_id], [type_code], [type_name], [rate_basis], [duration_basis], [standard_form_reference], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (4, N'COA', N'Contract of Affreightment', N'PER_TONNE', N'CONTRACT_PERIOD', NULL, N'Commitment to carry multiple cargoes of agreed total quantity over a period, owner nominates vessels per shipment.', 1, CAST(N'2026-07-12T11:19:44.3988082' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.3988082' AS DateTime2), N'SYSTEM')
INSERT [dbo].[charter_party_type] ([charter_party_type_id], [type_code], [type_name], [rate_basis], [duration_basis], [standard_form_reference], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (5, N'WS_VOYAGE', N'Voyage Charter — Worldscale', N'WORLDSCALE', N'SINGLE_VOYAGE', N'ASBATANKVOY', N'Voyage charter where freight is quoted as a % of the published Worldscale flat rate for the route.', 1, CAST(N'2026-07-12T11:19:44.3988082' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.3988082' AS DateTime2), N'SYSTEM')
SET IDENTITY_INSERT [dbo].[charter_party_type] OFF

SET IDENTITY_INSERT [dbo].[demurrage_dispatch_rate] ON 

INSERT [dbo].[demurrage_dispatch_rate] ([demurrage_rate_id], [vessel_type], [charter_party_type_id], [demurrage_rate_per_day], [dispatch_rate_per_day], [currency_id], [effective_from], [effective_to], [notes], [is_active], [created_at], [created_by], [updated_at], [updated_by], [claim_time_bar_days], [despatch_basis], [commodity_type]) VALUES (1, N'VLCC', 1, CAST(45000.00 AS Decimal(14, 2)), CAST(22500.00 AS Decimal(14, 2)), 1, CAST(N'2026-01-01' AS Date), NULL, N'Indicative default — confirm against fixture recap before use.', 1, CAST(N'2026-07-12T11:19:44.4142844' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4142844' AS DateTime2), N'SYSTEM', 90, N'ALL_TIME_SAVED', 1)
INSERT [dbo].[demurrage_dispatch_rate] ([demurrage_rate_id], [vessel_type], [charter_party_type_id], [demurrage_rate_per_day], [dispatch_rate_per_day], [currency_id], [effective_from], [effective_to], [notes], [is_active], [created_at], [created_by], [updated_at], [updated_by], [claim_time_bar_days], [despatch_basis], [commodity_type]) VALUES (2, N'SUEZMAX', 1, CAST(32000.00 AS Decimal(14, 2)), CAST(16000.00 AS Decimal(14, 2)), 1, CAST(N'2026-01-01' AS Date), NULL, N'Indicative default — confirm against fixture recap before use.', 1, CAST(N'2026-07-12T11:19:44.4142844' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4142844' AS DateTime2), N'SYSTEM', 90, N'ALL_TIME_SAVED', 1)
INSERT [dbo].[demurrage_dispatch_rate] ([demurrage_rate_id], [vessel_type], [charter_party_type_id], [demurrage_rate_per_day], [dispatch_rate_per_day], [currency_id], [effective_from], [effective_to], [notes], [is_active], [created_at], [created_by], [updated_at], [updated_by], [claim_time_bar_days], [despatch_basis], [commodity_type]) VALUES (3, N'AFRAMAX', 1, CAST(25000.00 AS Decimal(14, 2)), CAST(12500.00 AS Decimal(14, 2)), 1, CAST(N'2026-01-01' AS Date), NULL, N'Indicative default — confirm against fixture recap before use.', 1, CAST(N'2026-07-12T11:19:44.4142844' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4142844' AS DateTime2), N'SYSTEM', 90, N'ALL_TIME_SAVED', 1)
INSERT [dbo].[demurrage_dispatch_rate] ([demurrage_rate_id], [vessel_type], [charter_party_type_id], [demurrage_rate_per_day], [dispatch_rate_per_day], [currency_id], [effective_from], [effective_to], [notes], [is_active], [created_at], [created_by], [updated_at], [updated_by], [claim_time_bar_days], [despatch_basis], [commodity_type]) VALUES (4, N'PANAMAX', 1, CAST(18000.00 AS Decimal(14, 2)), CAST(9000.00 AS Decimal(14, 2)), 1, CAST(N'2026-01-01' AS Date), NULL, N'Indicative default — confirm against fixture recap before use.', 1, CAST(N'2026-07-12T11:19:44.4142844' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4142844' AS DateTime2), N'SYSTEM', 90, N'ALL_TIME_SAVED', 1)
INSERT [dbo].[demurrage_dispatch_rate] ([demurrage_rate_id], [vessel_type], [charter_party_type_id], [demurrage_rate_per_day], [dispatch_rate_per_day], [currency_id], [effective_from], [effective_to], [notes], [is_active], [created_at], [created_by], [updated_at], [updated_by], [claim_time_bar_days], [despatch_basis], [commodity_type]) VALUES (5, N'MR_TANKER', 1, CAST(12000.00 AS Decimal(14, 2)), CAST(6000.00 AS Decimal(14, 2)), 1, CAST(N'2026-01-01' AS Date), NULL, N'Indicative default — confirm against fixture recap before use.', 1, CAST(N'2026-07-12T11:19:44.4142844' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4142844' AS DateTime2), N'SYSTEM', 90, N'ALL_TIME_SAVED', 1)
INSERT [dbo].[demurrage_dispatch_rate] ([demurrage_rate_id], [vessel_type], [charter_party_type_id], [demurrage_rate_per_day], [dispatch_rate_per_day], [currency_id], [effective_from], [effective_to], [notes], [is_active], [created_at], [created_by], [updated_at], [updated_by], [claim_time_bar_days], [despatch_basis], [commodity_type]) VALUES (6, N'LNG_CARRIER', 2, CAST(100000.00 AS Decimal(14, 2)), CAST(50000.00 AS Decimal(14, 2)), 1, CAST(N'2026-01-01' AS Date), NULL, N'Indicative default — confirm against fixture recap before use.', 1, CAST(N'2026-07-12T11:19:47.9728148' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.9728148' AS DateTime2), N'SYSTEM', 90, N'ALL_TIME_SAVED', 4)
INSERT [dbo].[demurrage_dispatch_rate] ([demurrage_rate_id], [vessel_type], [charter_party_type_id], [demurrage_rate_per_day], [dispatch_rate_per_day], [currency_id], [effective_from], [effective_to], [notes], [is_active], [created_at], [created_by], [updated_at], [updated_by], [claim_time_bar_days], [despatch_basis], [commodity_type]) VALUES (7, N'BULK_CARRIER', 1, CAST(18000.00 AS Decimal(14, 2)), CAST(9000.00 AS Decimal(14, 2)), 1, CAST(N'2026-01-01' AS Date), NULL, N'Indicative default — confirm against fixture recap before use.', 1, CAST(N'2026-07-12T11:19:47.9728148' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.9728148' AS DateTime2), N'SYSTEM', 90, N'ALL_TIME_SAVED', 6)
SET IDENTITY_INSERT [dbo].[demurrage_dispatch_rate] OFF

SET IDENTITY_INSERT [dbo].[laytime_exception_type] ON 

INSERT [dbo].[laytime_exception_type] ([exception_type_id], [exception_code], [exception_name], [default_counts_against_laytime], [is_weather_related], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (1, N'WEATHER', N'Adverse Weather', 0, 1, N'Cargo work suspended due to weather (rain, high seas, wind) — excepted under Weather Working Days (WWD) templates.', 1, CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM')
INSERT [dbo].[laytime_exception_type] ([exception_type_id], [exception_code], [exception_name], [default_counts_against_laytime], [is_weather_related], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (2, N'STRIKE', N'Strike / Labour Action', 0, 0, N'Cargo work stopped by a strike at the port, terminal, or aboard the vessel.', 1, CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM')
INSERT [dbo].[laytime_exception_type] ([exception_type_id], [exception_code], [exception_name], [default_counts_against_laytime], [is_weather_related], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (3, N'BREAKDOWN', N'Equipment Breakdown', 0, 0, N'Ship''s gear, shore crane, pump, or loading arm breakdown halting cargo operations.', 1, CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM')
INSERT [dbo].[laytime_exception_type] ([exception_type_id], [exception_code], [exception_name], [default_counts_against_laytime], [is_weather_related], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (4, N'AWAITING_BERTH', N'Awaiting Berth', 1, 0, N'Vessel waiting for a berth to become available after NOR tender — counts against laytime unless the charter party is berth (not port) charter.', 1, CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM')
INSERT [dbo].[laytime_exception_type] ([exception_type_id], [exception_code], [exception_name], [default_counts_against_laytime], [is_weather_related], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (5, N'AWAITING_INSTRUCTIONS', N'Awaiting Charterer Instructions', 1, 0, N'Vessel idle awaiting discharge/loading instructions from the charterer or receiver.', 1, CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM')
INSERT [dbo].[laytime_exception_type] ([exception_type_id], [exception_code], [exception_name], [default_counts_against_laytime], [is_weather_related], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (6, N'HOLIDAY', N'Sunday / Holiday', 0, 0, N'Sunday or officially recognised holiday — excepted under SHEX-family templates, counts under SHINC.', 1, CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM')
INSERT [dbo].[laytime_exception_type] ([exception_type_id], [exception_code], [exception_name], [default_counts_against_laytime], [is_weather_related], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (7, N'PORT_CONGESTION', N'Port Congestion', 1, 0, N'General port congestion delaying berthing or cargo operations, not attributable to either party.', 1, CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM')
INSERT [dbo].[laytime_exception_type] ([exception_type_id], [exception_code], [exception_name], [default_counts_against_laytime], [is_weather_related], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (8, N'INSPECTION_DELAY', N'Inspection / Survey Delay', 0, 0, N'Delay for customs, quality, quantity, or regulatory inspection/survey before cargo work can proceed.', 1, CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM')
INSERT [dbo].[laytime_exception_type] ([exception_type_id], [exception_code], [exception_name], [default_counts_against_laytime], [is_weather_related], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (9, N'BOG_MANAGEMENT', N'Boil-Off Gas Management', 0, 0, N'LNG-specific: time spent managing boil-off gas beyond the guaranteed rate, cooldown, or heel adjustment at the load/discharge port.', 1, CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM')
INSERT [dbo].[laytime_exception_type] ([exception_type_id], [exception_code], [exception_name], [default_counts_against_laytime], [is_weather_related], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (10, N'FORCE_MAJEURE', N'Force Majeure', 0, 0, N'War, blockade, pandemic-related port closure, or other force majeure event outside either party''s control.', 1, CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM')
INSERT [dbo].[laytime_exception_type] ([exception_type_id], [exception_code], [exception_name], [default_counts_against_laytime], [is_weather_related], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (11, N'OTHER', N'Other', 1, 0, N'Other exception reason — see notes on the specific laytime/demurrage record.', 1, CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.9884538' AS DateTime2), N'SYSTEM')
SET IDENTITY_INSERT [dbo].[laytime_exception_type] OFF

SET IDENTITY_INSERT [dbo].[laytime_term_template] ON 

INSERT [dbo].[laytime_term_template] ([laytime_term_id], [term_code], [term_name], [exclusion_basis], [is_reversible], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [nor_wipon_allowed], [nor_wibon_allowed], [nor_wifpon_allowed], [nor_wccon_allowed], [notice_of_readiness_turn_time_mins], [commodity_type]) VALUES (1, N'SHINC', N'Sundays/Holidays Included', N'SHINC', 0, N'All days count against laytime regardless of Sundays or holidays.', 1, CAST(N'2026-07-12T11:19:44.4090312' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4090312' AS DateTime2), N'SYSTEM', 0, 0, 0, 0, 360, NULL)
INSERT [dbo].[laytime_term_template] ([laytime_term_id], [term_code], [term_name], [exclusion_basis], [is_reversible], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [nor_wipon_allowed], [nor_wibon_allowed], [nor_wifpon_allowed], [nor_wccon_allowed], [notice_of_readiness_turn_time_mins], [commodity_type]) VALUES (2, N'SHEX', N'Sundays/Holidays Excluded', N'SHEX', 0, N'Sundays and holidays do not count against laytime.', 1, CAST(N'2026-07-12T11:19:44.4090312' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4090312' AS DateTime2), N'SYSTEM', 1, 1, 1, 1, 360, NULL)
INSERT [dbo].[laytime_term_template] ([laytime_term_id], [term_code], [term_name], [exclusion_basis], [is_reversible], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [nor_wipon_allowed], [nor_wibon_allowed], [nor_wifpon_allowed], [nor_wccon_allowed], [notice_of_readiness_turn_time_mins], [commodity_type]) VALUES (3, N'SHEXEIU', N'SHEX Even If Used', N'SHEXEIU', 0, N'Sundays/holidays excluded from laytime even if cargo work actually takes place.', 1, CAST(N'2026-07-12T11:19:44.4090312' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4090312' AS DateTime2), N'SYSTEM', 1, 1, 1, 1, 360, NULL)
INSERT [dbo].[laytime_term_template] ([laytime_term_id], [term_code], [term_name], [exclusion_basis], [is_reversible], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [nor_wipon_allowed], [nor_wibon_allowed], [nor_wifpon_allowed], [nor_wccon_allowed], [notice_of_readiness_turn_time_mins], [commodity_type]) VALUES (4, N'SHEXUU', N'SHEX Unless Used', N'SHEXUU', 0, N'Sundays/holidays excluded from laytime unless cargo work actually takes place, in which case time used counts.', 1, CAST(N'2026-07-12T11:19:44.4090312' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4090312' AS DateTime2), N'SYSTEM', 1, 1, 1, 1, 360, NULL)
INSERT [dbo].[laytime_term_template] ([laytime_term_id], [term_code], [term_name], [exclusion_basis], [is_reversible], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [nor_wipon_allowed], [nor_wibon_allowed], [nor_wifpon_allowed], [nor_wccon_allowed], [notice_of_readiness_turn_time_mins], [commodity_type]) VALUES (5, N'WWD', N'Weather Working Days', N'WWD', 0, N'Only days/parts of days when weather permits cargo work count against laytime.', 1, CAST(N'2026-07-12T11:19:44.4090312' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4090312' AS DateTime2), N'SYSTEM', 0, 0, 0, 0, 360, NULL)
INSERT [dbo].[laytime_term_template] ([laytime_term_id], [term_code], [term_name], [exclusion_basis], [is_reversible], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [nor_wipon_allowed], [nor_wibon_allowed], [nor_wifpon_allowed], [nor_wccon_allowed], [notice_of_readiness_turn_time_mins], [commodity_type]) VALUES (6, N'WWDSHEXUU', N'Weather Working Days, SHEX Unless Used', N'WWDSHEXUU', 0, N'Combination: weather working days, with Sundays/holidays excluded unless used.', 1, CAST(N'2026-07-12T11:19:44.4090312' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4090312' AS DateTime2), N'SYSTEM', 1, 1, 1, 1, 360, NULL)
INSERT [dbo].[laytime_term_template] ([laytime_term_id], [term_code], [term_name], [exclusion_basis], [is_reversible], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [nor_wipon_allowed], [nor_wibon_allowed], [nor_wifpon_allowed], [nor_wccon_allowed], [notice_of_readiness_turn_time_mins], [commodity_type]) VALUES (7, N'WWD_REV', N'Weather Working Days — Reversible', N'WWD', 1, N'Weather working days with load and discharge laytime allowances pooled (reversible).', 1, CAST(N'2026-07-12T11:19:44.4090312' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4090312' AS DateTime2), N'SYSTEM', 1, 1, 1, 1, 360, NULL)
INSERT [dbo].[laytime_term_template] ([laytime_term_id], [term_code], [term_name], [exclusion_basis], [is_reversible], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [nor_wipon_allowed], [nor_wibon_allowed], [nor_wifpon_allowed], [nor_wccon_allowed], [notice_of_readiness_turn_time_mins], [commodity_type]) VALUES (8, N'LNG_SHINC', N'LNG Standard — SHINC, Non-Reversible', N'SHINC', 0, N'Standard LNG carrier laytime convention: continuous SHINC counting (LNG terminals operate 24/7 year-round) with the full WIPON/WIBON/WIFPON/WCCON NOR bundle and a 6-hour notice period. Laytime/demurrage calculations must additionally account for boil-off gas during port stays per the charter party''s BOG clause.', 1, CAST(N'2026-07-12T11:19:47.9184848' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.9184848' AS DateTime2), N'SYSTEM', 1, 1, 1, 1, 360, 4)
SET IDENTITY_INSERT [dbo].[laytime_term_template] OFF

SET IDENTITY_INSERT [dbo].[freight_rate_index] ON 

INSERT [dbo].[freight_rate_index] ([freight_rate_index_id], [index_code], [index_name], [index_type], [vessel_type], [route_description], [currency_id], [uom_id], [publication_source], [publication_frequency], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [commodity_type]) VALUES (1, N'BDTI', N'Baltic Dirty Tanker Index', N'BALTIC', NULL, NULL, 1, 22, N'Baltic Exchange', N'DAILY', N'Composite index tracking crude/dirty product tanker freight rates across major routes.', 1, CAST(N'2026-07-12T11:19:44.4039400' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4039400' AS DateTime2), N'SYSTEM', 1)
INSERT [dbo].[freight_rate_index] ([freight_rate_index_id], [index_code], [index_name], [index_type], [vessel_type], [route_description], [currency_id], [uom_id], [publication_source], [publication_frequency], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [commodity_type]) VALUES (2, N'BCTI', N'Baltic Clean Tanker Index', N'BALTIC', NULL, NULL, 1, 22, N'Baltic Exchange', N'DAILY', N'Composite index tracking clean petroleum product tanker freight rates.', 1, CAST(N'2026-07-12T11:19:44.4039400' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4039400' AS DateTime2), N'SYSTEM', 1)
INSERT [dbo].[freight_rate_index] ([freight_rate_index_id], [index_code], [index_name], [index_type], [vessel_type], [route_description], [currency_id], [uom_id], [publication_source], [publication_frequency], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [commodity_type]) VALUES (3, N'BDI', N'Baltic Dry Index', N'BALTIC', N'BULK_CARRIER', NULL, 1, 21, N'Baltic Exchange', N'DAILY', N'Composite dry bulk freight index (Capesize/Panamax/Supramax/Handysize).', 1, CAST(N'2026-07-12T11:19:44.4039400' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4039400' AS DateTime2), N'SYSTEM', NULL)
INSERT [dbo].[freight_rate_index] ([freight_rate_index_id], [index_code], [index_name], [index_type], [vessel_type], [route_description], [currency_id], [uom_id], [publication_source], [publication_frequency], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [commodity_type]) VALUES (4, N'BPI', N'Baltic Panamax Index', N'BALTIC', N'PANAMAX', NULL, 1, 21, N'Baltic Exchange', N'DAILY', N'Panamax dry bulk freight index.', 1, CAST(N'2026-07-12T11:19:44.4039400' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4039400' AS DateTime2), N'SYSTEM', NULL)
INSERT [dbo].[freight_rate_index] ([freight_rate_index_id], [index_code], [index_name], [index_type], [vessel_type], [route_description], [currency_id], [uom_id], [publication_source], [publication_frequency], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [commodity_type]) VALUES (5, N'BSI', N'Baltic Supramax Index', N'BALTIC', N'OTHER', NULL, 1, 21, N'Baltic Exchange', N'DAILY', N'Supramax dry bulk freight index.', 1, CAST(N'2026-07-12T11:19:44.4039400' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4039400' AS DateTime2), N'SYSTEM', NULL)
INSERT [dbo].[freight_rate_index] ([freight_rate_index_id], [index_code], [index_name], [index_type], [vessel_type], [route_description], [currency_id], [uom_id], [publication_source], [publication_frequency], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [commodity_type]) VALUES (6, N'BHSI', N'Baltic Handysize Index', N'BALTIC', N'HANDYSIZE', NULL, 1, 21, N'Baltic Exchange', N'DAILY', N'Handysize dry bulk freight index.', 1, CAST(N'2026-07-12T11:19:44.4039400' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4039400' AS DateTime2), N'SYSTEM', NULL)
INSERT [dbo].[freight_rate_index] ([freight_rate_index_id], [index_code], [index_name], [index_type], [vessel_type], [route_description], [currency_id], [uom_id], [publication_source], [publication_frequency], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [commodity_type]) VALUES (7, N'WS_FLAT_TD3C', N'Worldscale Flat Rate — TD3C (AG-China VLCC)', N'WORLDSCALE', N'VLCC', N'Arabian Gulf to China', NULL, NULL, N'Worldscale Association', N'ANNUAL', N'Annually published Worldscale 100 (WS100) flat rate in USD/tonne for the AG-China VLCC benchmark route.', 1, CAST(N'2026-07-12T11:19:44.4039400' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:44.4039400' AS DateTime2), N'SYSTEM', 1)
INSERT [dbo].[freight_rate_index] ([freight_rate_index_id], [index_code], [index_name], [index_type], [vessel_type], [route_description], [currency_id], [uom_id], [publication_source], [publication_frequency], [description], [is_active], [created_at], [created_by], [updated_at], [updated_by], [commodity_type]) VALUES (8, N'SPARK30S', N'Spark30S — LNG Freight Assessment (Atlantic)', N'ASSESSED', N'LNG_CARRIER', N'US Gulf-Continent / Atlantic LNG routes', 1, 21, N'Spark Commodities', N'DAILY', N'Daily-assessed LNG spot freight rate in USD/day for a 174,000cbm 2-stroke LNG carrier — the LNG market''s equivalent of a Baltic index.', 1, CAST(N'2026-07-12T11:19:47.8866910' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.8866910' AS DateTime2), N'SYSTEM', 4)
SET IDENTITY_INSERT [dbo].[freight_rate_index] OFF




