-- =============================================================================
-- SmartETRM — Reference/Seed Data: Pricing & Rates
-- =============================================================================
-- GENERATED FILE — do not hand-edit. Extracted from a live, fully-migrated
-- ETRM_DB (post-V96) via mssql-scripter, one table at a time.
--
-- REFERENCE ONLY — not guaranteed independently runnable in isolation.
-- SmartETRM's Master Data Hub groups are NOT a dependency hierarchy — most
-- groups have FKs pointing at each other in both directions (e.g. Products &
-- Markets needs Finance & Settlement's currency rows; Finance & Settlement's
-- bank_account needs Counterparties & Agreements' counterparty rows). There is
-- no group-by-group load order that satisfies every FK. For an actually-
-- runnable full load, use 01_master_data_seed.sql instead, which loads all
-- 154 tables' data in a verified-safe per-table order. This file exists so you
-- can find/read/diff "what's the seed data for Pricing & Rates" without wading through
-- the combined file.
--
-- Tables in this file (10): formula_template, fx_period, fx_rate, interest_rate_index, price_source, pricing_type, balmo_product, price_index_source, pricing_rule, settlement_price
-- =============================================================================

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


SET IDENTITY_INSERT [dbo].[fx_period] ON 

INSERT [dbo].[fx_period] ([fx_period_id], [period_code], [period_name], [period_type], [days_offset], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (1, N'SPOT', N'Spot Rate', N'SPOT', 0, 1, CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM')
INSERT [dbo].[fx_period] ([fx_period_id], [period_code], [period_name], [period_type], [days_offset], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (2, N'1M', N'1 Month Forward', N'STANDARD_TENOR', 30, 1, CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM')
INSERT [dbo].[fx_period] ([fx_period_id], [period_code], [period_name], [period_type], [days_offset], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (3, N'2M', N'2 Month Forward', N'STANDARD_TENOR', 60, 1, CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM')
INSERT [dbo].[fx_period] ([fx_period_id], [period_code], [period_name], [period_type], [days_offset], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (4, N'3M', N'3 Month Forward', N'STANDARD_TENOR', 90, 1, CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM')
INSERT [dbo].[fx_period] ([fx_period_id], [period_code], [period_name], [period_type], [days_offset], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (5, N'6M', N'6 Month Forward', N'STANDARD_TENOR', 180, 1, CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM')
INSERT [dbo].[fx_period] ([fx_period_id], [period_code], [period_name], [period_type], [days_offset], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (6, N'9M', N'9 Month Forward', N'STANDARD_TENOR', 270, 1, CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM')
INSERT [dbo].[fx_period] ([fx_period_id], [period_code], [period_name], [period_type], [days_offset], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (7, N'1Y', N'1 Year Forward', N'STANDARD_TENOR', 365, 1, CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM')
INSERT [dbo].[fx_period] ([fx_period_id], [period_code], [period_name], [period_type], [days_offset], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (8, N'2Y', N'2 Year Forward', N'STANDARD_TENOR', 730, 1, CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM')
INSERT [dbo].[fx_period] ([fx_period_id], [period_code], [period_name], [period_type], [days_offset], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (9, N'DAY_1', N'Day 1 Forward', N'DAILY_FORWARD', 1, 1, CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM')
INSERT [dbo].[fx_period] ([fx_period_id], [period_code], [period_name], [period_type], [days_offset], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (10, N'DAY_2', N'Day 2 Forward', N'DAILY_FORWARD', 2, 1, CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM')
INSERT [dbo].[fx_period] ([fx_period_id], [period_code], [period_name], [period_type], [days_offset], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (11, N'DAY_3', N'Day 3 Forward', N'DAILY_FORWARD', 3, 1, CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:48.3917215' AS DateTime2), N'SYSTEM')
SET IDENTITY_INSERT [dbo].[fx_period] OFF


SET IDENTITY_INSERT [dbo].[interest_rate_index] ON 

INSERT [dbo].[interest_rate_index] ([rate_index_id], [index_code], [index_name], [currency_id], [tenor], [day_count_convention], [compounding], [publication_source], [publication_time], [fixing_lag_days], [is_rfrr], [replaces_index_id], [is_active], [description]) VALUES (1, N'SOFR', N'Secured Overnight Financing Rate', 1, N'OVERNIGHT', N'ACT_360', N'OVERNIGHT_COMPOUNDED', N'NY Fed', NULL, 0, 1, NULL, 1, NULL)
INSERT [dbo].[interest_rate_index] ([rate_index_id], [index_code], [index_name], [currency_id], [tenor], [day_count_convention], [compounding], [publication_source], [publication_time], [fixing_lag_days], [is_rfrr], [replaces_index_id], [is_active], [description]) VALUES (2, N'SOFR_1M', N'SOFR Term 1 Month', 1, N'1M', N'ACT_360', N'SIMPLE', N'CME Group', NULL, 0, 1, NULL, 1, NULL)
INSERT [dbo].[interest_rate_index] ([rate_index_id], [index_code], [index_name], [currency_id], [tenor], [day_count_convention], [compounding], [publication_source], [publication_time], [fixing_lag_days], [is_rfrr], [replaces_index_id], [is_active], [description]) VALUES (3, N'SOFR_3M', N'SOFR Term 3 Month', 1, N'3M', N'ACT_360', N'SIMPLE', N'CME Group', NULL, 0, 1, NULL, 1, NULL)
INSERT [dbo].[interest_rate_index] ([rate_index_id], [index_code], [index_name], [currency_id], [tenor], [day_count_convention], [compounding], [publication_source], [publication_time], [fixing_lag_days], [is_rfrr], [replaces_index_id], [is_active], [description]) VALUES (4, N'EURIBOR_1M', N'Euro Interbank Offered Rate 1 Month', 2, N'1M', N'ACT_360', N'SIMPLE', N'EMMI', NULL, 0, 0, NULL, 1, NULL)
INSERT [dbo].[interest_rate_index] ([rate_index_id], [index_code], [index_name], [currency_id], [tenor], [day_count_convention], [compounding], [publication_source], [publication_time], [fixing_lag_days], [is_rfrr], [replaces_index_id], [is_active], [description]) VALUES (5, N'EURIBOR_3M', N'Euro Interbank Offered Rate 3 Month', 2, N'3M', N'ACT_360', N'SIMPLE', N'EMMI', NULL, 0, 0, NULL, 1, NULL)
INSERT [dbo].[interest_rate_index] ([rate_index_id], [index_code], [index_name], [currency_id], [tenor], [day_count_convention], [compounding], [publication_source], [publication_time], [fixing_lag_days], [is_rfrr], [replaces_index_id], [is_active], [description]) VALUES (6, N'EURIBOR_6M', N'Euro Interbank Offered Rate 6 Month', 2, N'6M', N'ACT_360', N'SIMPLE', N'EMMI', NULL, 0, 0, NULL, 1, NULL)
INSERT [dbo].[interest_rate_index] ([rate_index_id], [index_code], [index_name], [currency_id], [tenor], [day_count_convention], [compounding], [publication_source], [publication_time], [fixing_lag_days], [is_rfrr], [replaces_index_id], [is_active], [description]) VALUES (7, N'ESTR', N'Euro Short-Term Rate', 2, N'OVERNIGHT', N'ACT_360', N'OVERNIGHT_COMPOUNDED', N'ECB', NULL, 0, 1, NULL, 1, NULL)
INSERT [dbo].[interest_rate_index] ([rate_index_id], [index_code], [index_name], [currency_id], [tenor], [day_count_convention], [compounding], [publication_source], [publication_time], [fixing_lag_days], [is_rfrr], [replaces_index_id], [is_active], [description]) VALUES (8, N'SONIA', N'Sterling Overnight Index Average', 3, N'OVERNIGHT', N'ACT_365', N'OVERNIGHT_COMPOUNDED', N'BoE', NULL, 0, 1, NULL, 1, NULL)
INSERT [dbo].[interest_rate_index] ([rate_index_id], [index_code], [index_name], [currency_id], [tenor], [day_count_convention], [compounding], [publication_source], [publication_time], [fixing_lag_days], [is_rfrr], [replaces_index_id], [is_active], [description]) VALUES (9, N'SONIA_3M', N'SONIA Compounded 3 Month', 3, N'3M', N'ACT_365', N'COMPOUNDED', N'BoE', NULL, 0, 1, NULL, 1, NULL)
INSERT [dbo].[interest_rate_index] ([rate_index_id], [index_code], [index_name], [currency_id], [tenor], [day_count_convention], [compounding], [publication_source], [publication_time], [fixing_lag_days], [is_rfrr], [replaces_index_id], [is_active], [description]) VALUES (10, N'TONAR', N'Tokyo Overnight Average Rate', 4, N'OVERNIGHT', N'ACT_365', N'OVERNIGHT_COMPOUNDED', N'BoJ', NULL, 0, 1, NULL, 1, NULL)
INSERT [dbo].[interest_rate_index] ([rate_index_id], [index_code], [index_name], [currency_id], [tenor], [day_count_convention], [compounding], [publication_source], [publication_time], [fixing_lag_days], [is_rfrr], [replaces_index_id], [is_active], [description]) VALUES (11, N'FEDFUNDS', N'US Federal Funds Rate', 1, N'OVERNIGHT', N'ACT_360', N'SIMPLE', N'Federal Reserve', NULL, 0, 0, NULL, 1, NULL)
INSERT [dbo].[interest_rate_index] ([rate_index_id], [index_code], [index_name], [currency_id], [tenor], [day_count_convention], [compounding], [publication_source], [publication_time], [fixing_lag_days], [is_rfrr], [replaces_index_id], [is_active], [description]) VALUES (12, N'PRIME_USD', N'US Prime Rate', 1, N'OVERNIGHT', N'ACT_360', N'SIMPLE', N'WSJ', NULL, 0, 0, NULL, 1, NULL)
SET IDENTITY_INSERT [dbo].[interest_rate_index] OFF

SET IDENTITY_INSERT [dbo].[price_source] ON 

INSERT [dbo].[price_source] ([price_source_id], [source_code], [source_name], [source_type], [delivery_method], [frequency], [timezone], [base_url], [credentials_ref], [sla_minutes], [is_active], [notes], [created_at], [created_by], [updated_at], [updated_by]) VALUES (1, N'PLATTS', N'S&P Global Platts', N'VENDOR', N'API', N'EOD', N'Europe/London', NULL, NULL, NULL, 1, NULL, CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM')
INSERT [dbo].[price_source] ([price_source_id], [source_code], [source_name], [source_type], [delivery_method], [frequency], [timezone], [base_url], [credentials_ref], [sla_minutes], [is_active], [notes], [created_at], [created_by], [updated_at], [updated_by]) VALUES (2, N'ARGUS', N'Argus Media', N'VENDOR', N'API', N'EOD', N'Europe/London', NULL, NULL, NULL, 1, NULL, CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM')
INSERT [dbo].[price_source] ([price_source_id], [source_code], [source_name], [source_type], [delivery_method], [frequency], [timezone], [base_url], [credentials_ref], [sla_minutes], [is_active], [notes], [created_at], [created_by], [updated_at], [updated_by]) VALUES (3, N'BLOOMBERG', N'Bloomberg', N'BLOOMBERG', N'REAL_TIME_FEED', N'REAL_TIME', N'America/New_York', NULL, NULL, NULL, 1, NULL, CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM')
INSERT [dbo].[price_source] ([price_source_id], [source_code], [source_name], [source_type], [delivery_method], [frequency], [timezone], [base_url], [credentials_ref], [sla_minutes], [is_active], [notes], [created_at], [created_by], [updated_at], [updated_by]) VALUES (4, N'REUTERS', N'Refinitiv/Reuters', N'REUTERS', N'REAL_TIME_FEED', N'REAL_TIME', N'America/New_York', NULL, NULL, NULL, 1, NULL, CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM')
INSERT [dbo].[price_source] ([price_source_id], [source_code], [source_name], [source_type], [delivery_method], [frequency], [timezone], [base_url], [credentials_ref], [sla_minutes], [is_active], [notes], [created_at], [created_by], [updated_at], [updated_by]) VALUES (5, N'ICE_DATA', N'ICE Data Services', N'EXCHANGE', N'API', N'EOD', N'Europe/London', NULL, NULL, NULL, 1, NULL, CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM')
INSERT [dbo].[price_source] ([price_source_id], [source_code], [source_name], [source_type], [delivery_method], [frequency], [timezone], [base_url], [credentials_ref], [sla_minutes], [is_active], [notes], [created_at], [created_by], [updated_at], [updated_by]) VALUES (6, N'NYMEX_DATA', N'CME Group Market Data', N'EXCHANGE', N'API', N'EOD', N'America/New_York', NULL, NULL, NULL, 1, NULL, CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM')
INSERT [dbo].[price_source] ([price_source_id], [source_code], [source_name], [source_type], [delivery_method], [frequency], [timezone], [base_url], [credentials_ref], [sla_minutes], [is_active], [notes], [created_at], [created_by], [updated_at], [updated_by]) VALUES (7, N'LME_DATA', N'LME Official Prices', N'EXCHANGE', N'API', N'EOD', N'Europe/London', NULL, NULL, NULL, 1, NULL, CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM')
INSERT [dbo].[price_source] ([price_source_id], [source_code], [source_name], [source_type], [delivery_method], [frequency], [timezone], [base_url], [credentials_ref], [sla_minutes], [is_active], [notes], [created_at], [created_by], [updated_at], [updated_by]) VALUES (8, N'EEX_DATA', N'EEX Market Data', N'EXCHANGE', N'API', N'EOD', N'Europe/Berlin', NULL, NULL, NULL, 1, NULL, CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM')
INSERT [dbo].[price_source] ([price_source_id], [source_code], [source_name], [source_type], [delivery_method], [frequency], [timezone], [base_url], [credentials_ref], [sla_minutes], [is_active], [notes], [created_at], [created_by], [updated_at], [updated_by]) VALUES (9, N'ICIS', N'ICIS Price Assessments', N'VENDOR', N'FTP', N'EOD', N'Europe/London', NULL, NULL, NULL, 1, NULL, CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM')
INSERT [dbo].[price_source] ([price_source_id], [source_code], [source_name], [source_type], [delivery_method], [frequency], [timezone], [base_url], [credentials_ref], [sla_minutes], [is_active], [notes], [created_at], [created_by], [updated_at], [updated_by]) VALUES (10, N'INTERNAL', N'Internal / Manual Entry', N'INTERNAL', N'MANUAL', N'MANUAL', N'UTC', NULL, NULL, NULL, 1, NULL, CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:43.6931306' AS DateTime2), N'SYSTEM')
SET IDENTITY_INSERT [dbo].[price_source] OFF

SET IDENTITY_INSERT [dbo].[pricing_type] ON 

INSERT [dbo].[pricing_type] ([pricing_type_id], [type_code], [type_name], [description], [requires_index], [requires_formula], [is_active]) VALUES (1, N'FLAT', N'Flat Price', N'Fixed price agreed at trade date. No index reference.', 0, 0, 1)
INSERT [dbo].[pricing_type] ([pricing_type_id], [type_code], [type_name], [description], [requires_index], [requires_formula], [is_active]) VALUES (2, N'INDEX', N'Index Price', N'Price equals a named index on a specified date.', 1, 0, 1)
INSERT [dbo].[pricing_type] ([pricing_type_id], [type_code], [type_name], [description], [requires_index], [requires_formula], [is_active]) VALUES (3, N'DIFFERENTIAL', N'Differential', N'Index price plus or minus a fixed differential (basis).', 1, 0, 1)
INSERT [dbo].[pricing_type] ([pricing_type_id], [type_code], [type_name], [description], [requires_index], [requires_formula], [is_active]) VALUES (4, N'FORMULA', N'Formula Price', N'Price determined by a formula referencing one or more indices.', 1, 1, 1)
INSERT [dbo].[pricing_type] ([pricing_type_id], [type_code], [type_name], [description], [requires_index], [requires_formula], [is_active]) VALUES (5, N'FLOATING', N'Floating Average', N'Average of index over a defined pricing period.', 1, 0, 1)
INSERT [dbo].[pricing_type] ([pricing_type_id], [type_code], [type_name], [description], [requires_index], [requires_formula], [is_active]) VALUES (6, N'TBN', N'To Be Nominated', N'Price not yet fixed — to be nominated at a future date.', 0, 0, 1)
INSERT [dbo].[pricing_type] ([pricing_type_id], [type_code], [type_name], [description], [requires_index], [requires_formula], [is_active]) VALUES (7, N'TAS', N'Trade at Settlement (TAS)', N'Price = exchange daily settlement ± differential in ticks. Unknown at execution; locked when exchange publishes settlement.', 0, 0, 1)
INSERT [dbo].[pricing_type] ([pricing_type_id], [type_code], [type_name], [description], [requires_index], [requires_formula], [is_active]) VALUES (8, N'OPTION_STRIKE', N'Option Strike', N'Price determined by the strike price of an option contract at exercise.', 0, 0, 1)
INSERT [dbo].[pricing_type] ([pricing_type_id], [type_code], [type_name], [description], [requires_index], [requires_formula], [is_active]) VALUES (9, N'PLATTS_WINDOW', N'Platts MOC Window', N'Price assessed during the Platts Market on Close (MOC) submission window.', 1, 0, 1)
INSERT [dbo].[pricing_type] ([pricing_type_id], [type_code], [type_name], [description], [requires_index], [requires_formula], [is_active]) VALUES (10, N'BALMO', N'Balance of Month (BALMO)', N'Exchange-cleared partial-month average price swap. Pricing window = booking date ? last business day of contract month. Floating price = arithmetic average of daily front-month futures settlements over that window.', 1, 0, 1)
SET IDENTITY_INSERT [dbo].[pricing_type] OFF

SET IDENTITY_INSERT [dbo].[balmo_product] ON 

INSERT [dbo].[balmo_product] ([balmo_product_id], [product_code], [product_name], [exchange], [contract_series], [contract_month], [pricing_start_date], [pricing_end_date], [last_trading_date], [settlement_price_ticker], [tick_size], [price_source], [status], [notes], [created_at], [updated_at], [uom_id], [tick_currency_id]) VALUES (1, N'BALMO-CL-2026-07', N'WTI Crude CL Balance of Month July 2026', N'CME_NYMEX', N'CL', N'2026-07', CAST(N'2026-07-01' AS Date), CAST(N'2026-07-31' AS Date), CAST(N'2026-07-01' AS Date), N'CLN26', CAST(0.010000 AS Decimal(12, 6)), N'CME', N'ACTIVE', N'CME NYMEX WTI BALMO Jul26 — front month CLN26 settlements averaged over pricing window', CAST(N'2026-07-12T11:19:47.1487152' AS DateTime2), CAST(N'2026-07-12T11:19:47.1487152' AS DateTime2), 1, 1)
INSERT [dbo].[balmo_product] ([balmo_product_id], [product_code], [product_name], [exchange], [contract_series], [contract_month], [pricing_start_date], [pricing_end_date], [last_trading_date], [settlement_price_ticker], [tick_size], [price_source], [status], [notes], [created_at], [updated_at], [uom_id], [tick_currency_id]) VALUES (2, N'BALMO-CL-2026-08', N'WTI Crude CL Balance of Month August 2026', N'CME_NYMEX', N'CL', N'2026-08', CAST(N'2026-08-01' AS Date), CAST(N'2026-08-29' AS Date), CAST(N'2026-08-01' AS Date), N'CLQ26', CAST(0.010000 AS Decimal(12, 6)), N'CME', N'ACTIVE', N'CME NYMEX WTI BALMO Aug26 — front month CLQ26 settlements', CAST(N'2026-07-12T11:19:47.1487152' AS DateTime2), CAST(N'2026-07-12T11:19:47.1487152' AS DateTime2), 1, 1)
INSERT [dbo].[balmo_product] ([balmo_product_id], [product_code], [product_name], [exchange], [contract_series], [contract_month], [pricing_start_date], [pricing_end_date], [last_trading_date], [settlement_price_ticker], [tick_size], [price_source], [status], [notes], [created_at], [updated_at], [uom_id], [tick_currency_id]) VALUES (3, N'BALMO-BZ-2026-07', N'ICE Brent BZ Balance of Month July 2026', N'ICE_EUROPE', N'BZ', N'2026-07', CAST(N'2026-07-01' AS Date), CAST(N'2026-07-31' AS Date), CAST(N'2026-07-01' AS Date), N'BZN26', CAST(0.010000 AS Decimal(12, 6)), N'ICE', N'ACTIVE', N'ICE Brent BALMO Jul26 — BZN26 daily settlements averaged', CAST(N'2026-07-12T11:19:47.1487152' AS DateTime2), CAST(N'2026-07-12T11:19:47.1487152' AS DateTime2), 1, 1)
INSERT [dbo].[balmo_product] ([balmo_product_id], [product_code], [product_name], [exchange], [contract_series], [contract_month], [pricing_start_date], [pricing_end_date], [last_trading_date], [settlement_price_ticker], [tick_size], [price_source], [status], [notes], [created_at], [updated_at], [uom_id], [tick_currency_id]) VALUES (4, N'BALMO-HO-2026-07', N'Heating Oil HO Balance of Month July 2026', N'CME_NYMEX', N'HO', N'2026-07', CAST(N'2026-07-01' AS Date), CAST(N'2026-07-31' AS Date), CAST(N'2026-07-01' AS Date), N'HON26', CAST(0.000100 AS Decimal(12, 6)), N'CME', N'ACTIVE', N'CME NYMEX ULSD/Heating Oil BALMO Jul26 — HON26 settlements', CAST(N'2026-07-12T11:19:47.1487152' AS DateTime2), CAST(N'2026-07-12T11:19:47.1487152' AS DateTime2), 19, 1)
SET IDENTITY_INSERT [dbo].[balmo_product] OFF


SET IDENTITY_INSERT [dbo].[pricing_rule] ON 

INSERT [dbo].[pricing_rule] ([pricing_rule_id], [product_id], [market_id], [incoterm_id], [pricing_type_id], [price_index_id], [formula_template_id], [differential_value], [differential_currency_id], [primary_trigger_id], [fallback_trigger_id], [fallback_deadline_days], [fallback_deadline_basis], [window_rule_id], [index_currency_id], [trade_currency_id], [fx_conversion_required], [fx_fixing_type], [fx_index_id], [late_pricing_rule], [provisional_basis], [price_decimal_places], [quantity_decimal_places], [value_decimal_places], [rounding_convention], [invoice_trigger_id], [invoice_timing_days], [invoice_timing_basis], [invoice_calendar_id], [requires_final_invoice], [final_invoice_trigger_id], [rule_name], [rule_code], [is_default], [effective_from], [effective_to], [is_active], [notes], [created_at], [created_by], [updated_at], [updated_by], [tas_exchange], [tas_contract_series], [tas_tick_size]) VALUES (1, 5, NULL, NULL, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, 2, 3, 2, N'STANDARD', NULL, 0, N'BUSINESS', NULL, 0, NULL, N'WTI Crude CL Trade at Settlement', N'TAS-NYMEX-CL', 0, CAST(N'2020-01-01' AS Date), NULL, 1, NULL, CAST(N'2026-07-12T11:19:47.0709669' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.0709669' AS DateTime2), N'SYSTEM', N'CME_NYMEX', N'CL', CAST(0.010000 AS Decimal(12, 6)))
INSERT [dbo].[pricing_rule] ([pricing_rule_id], [product_id], [market_id], [incoterm_id], [pricing_type_id], [price_index_id], [formula_template_id], [differential_value], [differential_currency_id], [primary_trigger_id], [fallback_trigger_id], [fallback_deadline_days], [fallback_deadline_basis], [window_rule_id], [index_currency_id], [trade_currency_id], [fx_conversion_required], [fx_fixing_type], [fx_index_id], [late_pricing_rule], [provisional_basis], [price_decimal_places], [quantity_decimal_places], [value_decimal_places], [rounding_convention], [invoice_trigger_id], [invoice_timing_days], [invoice_timing_basis], [invoice_calendar_id], [requires_final_invoice], [final_invoice_trigger_id], [rule_name], [rule_code], [is_default], [effective_from], [effective_to], [is_active], [notes], [created_at], [created_by], [updated_at], [updated_by], [tas_exchange], [tas_contract_series], [tas_tick_size]) VALUES (2, 8, NULL, NULL, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, 2, 3, 2, N'STANDARD', NULL, 0, N'BUSINESS', NULL, 0, NULL, N'Henry Hub NG Trade at Settlement', N'TAS-NYMEX-NG', 0, CAST(N'2020-01-01' AS Date), NULL, 1, NULL, CAST(N'2026-07-12T11:19:47.0709669' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.0709669' AS DateTime2), N'SYSTEM', N'CME_NYMEX', N'NG', CAST(0.001000 AS Decimal(12, 6)))
INSERT [dbo].[pricing_rule] ([pricing_rule_id], [product_id], [market_id], [incoterm_id], [pricing_type_id], [price_index_id], [formula_template_id], [differential_value], [differential_currency_id], [primary_trigger_id], [fallback_trigger_id], [fallback_deadline_days], [fallback_deadline_basis], [window_rule_id], [index_currency_id], [trade_currency_id], [fx_conversion_required], [fx_fixing_type], [fx_index_id], [late_pricing_rule], [provisional_basis], [price_decimal_places], [quantity_decimal_places], [value_decimal_places], [rounding_convention], [invoice_trigger_id], [invoice_timing_days], [invoice_timing_basis], [invoice_calendar_id], [requires_final_invoice], [final_invoice_trigger_id], [rule_name], [rule_code], [is_default], [effective_from], [effective_to], [is_active], [notes], [created_at], [created_by], [updated_at], [updated_by], [tas_exchange], [tas_contract_series], [tas_tick_size]) VALUES (3, 9, NULL, NULL, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, 2, 3, 2, N'STANDARD', NULL, 0, N'BUSINESS', NULL, 0, NULL, N'Heating Oil HO Trade at Settlement', N'TAS-NYMEX-HO', 0, CAST(N'2020-01-01' AS Date), NULL, 1, NULL, CAST(N'2026-07-12T11:19:47.0709669' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.0709669' AS DateTime2), N'SYSTEM', N'CME_NYMEX', N'HO', CAST(0.000100 AS Decimal(12, 6)))
INSERT [dbo].[pricing_rule] ([pricing_rule_id], [product_id], [market_id], [incoterm_id], [pricing_type_id], [price_index_id], [formula_template_id], [differential_value], [differential_currency_id], [primary_trigger_id], [fallback_trigger_id], [fallback_deadline_days], [fallback_deadline_basis], [window_rule_id], [index_currency_id], [trade_currency_id], [fx_conversion_required], [fx_fixing_type], [fx_index_id], [late_pricing_rule], [provisional_basis], [price_decimal_places], [quantity_decimal_places], [value_decimal_places], [rounding_convention], [invoice_trigger_id], [invoice_timing_days], [invoice_timing_basis], [invoice_calendar_id], [requires_final_invoice], [final_invoice_trigger_id], [rule_name], [rule_code], [is_default], [effective_from], [effective_to], [is_active], [notes], [created_at], [created_by], [updated_at], [updated_by], [tas_exchange], [tas_contract_series], [tas_tick_size]) VALUES (4, 4, NULL, NULL, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, 2, 3, 2, N'STANDARD', NULL, 0, N'BUSINESS', NULL, 0, NULL, N'ICE Brent BZ Trade at Settlement', N'TAS-ICE-BZ', 0, CAST(N'2020-01-01' AS Date), NULL, 1, NULL, CAST(N'2026-07-12T11:19:47.0709669' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:47.0709669' AS DateTime2), N'SYSTEM', N'ICE_EUROPE', N'BZ', CAST(0.010000 AS Decimal(12, 6)))
SET IDENTITY_INSERT [dbo].[pricing_rule] OFF

SET IDENTITY_INSERT [dbo].[settlement_price] ON 

INSERT [dbo].[settlement_price] ([settlement_price_id], [exchange], [contract_ticker], [settle_date], [settle_price], [tick_size], [is_confirmed], [source], [notes], [created_at], [updated_at], [uom_id], [tick_currency_id]) VALUES (1, N'CME_NYMEX', N'CLZ26', CAST(N'2026-07-01' AS Date), CAST(72.450000 AS Decimal(18, 6)), CAST(0.010000 AS Decimal(12, 6)), 1, N'CME', NULL, CAST(N'2026-07-12T11:19:47.0807391' AS DateTime2), CAST(N'2026-07-12T11:19:47.0807391' AS DateTime2), 1, 1)
INSERT [dbo].[settlement_price] ([settlement_price_id], [exchange], [contract_ticker], [settle_date], [settle_price], [tick_size], [is_confirmed], [source], [notes], [created_at], [updated_at], [uom_id], [tick_currency_id]) VALUES (2, N'CME_NYMEX', N'CLF27', CAST(N'2026-07-01' AS Date), CAST(71.800000 AS Decimal(18, 6)), CAST(0.010000 AS Decimal(12, 6)), 1, N'CME', NULL, CAST(N'2026-07-12T11:19:47.0807391' AS DateTime2), CAST(N'2026-07-12T11:19:47.0807391' AS DateTime2), 1, 1)
INSERT [dbo].[settlement_price] ([settlement_price_id], [exchange], [contract_ticker], [settle_date], [settle_price], [tick_size], [is_confirmed], [source], [notes], [created_at], [updated_at], [uom_id], [tick_currency_id]) VALUES (3, N'CME_NYMEX', N'NGF27', CAST(N'2026-07-01' AS Date), CAST(3.456000 AS Decimal(18, 6)), CAST(0.001000 AS Decimal(12, 6)), 1, N'CME', NULL, CAST(N'2026-07-12T11:19:47.0807391' AS DateTime2), CAST(N'2026-07-12T11:19:47.0807391' AS DateTime2), 7, 1)
INSERT [dbo].[settlement_price] ([settlement_price_id], [exchange], [contract_ticker], [settle_date], [settle_price], [tick_size], [is_confirmed], [source], [notes], [created_at], [updated_at], [uom_id], [tick_currency_id]) VALUES (4, N'CME_NYMEX', N'HOF27', CAST(N'2026-07-01' AS Date), CAST(2.342100 AS Decimal(18, 6)), CAST(0.000100 AS Decimal(12, 6)), 1, N'CME', NULL, CAST(N'2026-07-12T11:19:47.0807391' AS DateTime2), CAST(N'2026-07-12T11:19:47.0807391' AS DateTime2), 19, 1)
INSERT [dbo].[settlement_price] ([settlement_price_id], [exchange], [contract_ticker], [settle_date], [settle_price], [tick_size], [is_confirmed], [source], [notes], [created_at], [updated_at], [uom_id], [tick_currency_id]) VALUES (5, N'ICE_EUROPE', N'BZF27', CAST(N'2026-07-01' AS Date), CAST(76.230000 AS Decimal(18, 6)), CAST(0.010000 AS Decimal(12, 6)), 1, N'ICE', NULL, CAST(N'2026-07-12T11:19:47.0807391' AS DateTime2), CAST(N'2026-07-12T11:19:47.0807391' AS DateTime2), 1, 1)
INSERT [dbo].[settlement_price] ([settlement_price_id], [exchange], [contract_ticker], [settle_date], [settle_price], [tick_size], [is_confirmed], [source], [notes], [created_at], [updated_at], [uom_id], [tick_currency_id]) VALUES (6, N'CME_NYMEX', N'CLZ26', CAST(N'2026-06-30' AS Date), CAST(72.180000 AS Decimal(18, 6)), CAST(0.010000 AS Decimal(12, 6)), 1, N'CME', NULL, CAST(N'2026-07-12T11:19:47.0807391' AS DateTime2), CAST(N'2026-07-12T11:19:47.0807391' AS DateTime2), 1, 1)
INSERT [dbo].[settlement_price] ([settlement_price_id], [exchange], [contract_ticker], [settle_date], [settle_price], [tick_size], [is_confirmed], [source], [notes], [created_at], [updated_at], [uom_id], [tick_currency_id]) VALUES (7, N'CME_NYMEX', N'NGF27', CAST(N'2026-06-30' AS Date), CAST(3.456000 AS Decimal(18, 6)), CAST(0.001000 AS Decimal(12, 6)), 1, N'CME', NULL, CAST(N'2026-07-12T11:19:47.0807391' AS DateTime2), CAST(N'2026-07-12T11:19:47.0807391' AS DateTime2), 7, 1)
SET IDENTITY_INSERT [dbo].[settlement_price] OFF

