-- =============================================================================
-- SmartETRM — Reference/Seed Data: Shared Support Tables
-- =============================================================================
-- GENERATED FILE — do not hand-edit. Extracted from a live, fully-migrated
-- ETRM_DB (post-V96) via mssql-scripter, one table at a time.
--
-- REFERENCE ONLY — not guaranteed independently runnable in isolation.
-- SmartETRM's Master Data Hub groups are NOT a dependency hierarchy — most
-- groups have FKs pointing at each other in both directions (e.g. Products &
-- Markets needs Finance & Settlement's currency rows; Finance & Settlement's
-- bank_account needs Counterparties & Agreements' counterparty rows). There is
-- no group-by-group load order that satisfies every FK. For an actually-
-- runnable full load, use 01_master_data_seed.sql instead, which loads all
-- 154 tables' data in a verified-safe per-table order. This file exists so you
-- can find/read/diff "what's the seed data for Shared Support Tables" without wading through
-- the combined file.
--
-- Tables in this file (8): address, document_store, field_permission_profile, gtc_version, pricing_trigger_event_type, screen_field_registry, pricing_window_rule, pipeline_point
-- =============================================================================

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



SET IDENTITY_INSERT [dbo].[field_permission_profile] ON 

INSERT [dbo].[field_permission_profile] ([profile_id], [profile_code], [profile_name], [description], [screen_code], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (1, N'TRADE_BLOTTER_TRADER', N'Trader — Full Access', N'Full edit access to all trade fields', N'TRADE_BLOTTER', 1, CAST(N'2026-07-12T11:19:46.5509992' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:46.5509992' AS DateTime2), N'SYSTEM')
INSERT [dbo].[field_permission_profile] ([profile_id], [profile_code], [profile_name], [description], [screen_code], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (2, N'TRADE_BLOTTER_CREDIT_MGR', N'Credit Manager', N'Can approve trades and add notes; cannot edit commercial or logistics terms', N'TRADE_BLOTTER', 1, CAST(N'2026-07-12T11:19:46.5509992' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:46.5509992' AS DateTime2), N'SYSTEM')
INSERT [dbo].[field_permission_profile] ([profile_id], [profile_code], [profile_name], [description], [screen_code], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (3, N'TRADE_BLOTTER_RISK', N'Risk Manager', N'Can view all fields and approve; cannot edit prices or counterparty details', N'TRADE_BLOTTER', 1, CAST(N'2026-07-12T11:19:46.5509992' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:46.5509992' AS DateTime2), N'SYSTEM')
INSERT [dbo].[field_permission_profile] ([profile_id], [profile_code], [profile_name], [description], [screen_code], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (4, N'TRADE_BLOTTER_VIEWER', N'Read-Only Viewer', N'View-only access to all trade fields', N'TRADE_BLOTTER', 1, CAST(N'2026-07-12T11:19:46.5509992' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:46.5509992' AS DateTime2), N'SYSTEM')
INSERT [dbo].[field_permission_profile] ([profile_id], [profile_code], [profile_name], [description], [screen_code], [is_active], [created_at], [created_by], [updated_at], [updated_by]) VALUES (5, N'TRADE_BLOTTER_OPS', N'Operations', N'Can edit logistics and scheduling fields; commercial terms are view-only', N'TRADE_BLOTTER', 1, CAST(N'2026-07-12T11:19:46.5509992' AS DateTime2), N'SYSTEM', CAST(N'2026-07-12T11:19:46.5509992' AS DateTime2), N'SYSTEM')
SET IDENTITY_INSERT [dbo].[field_permission_profile] OFF


SET IDENTITY_INSERT [dbo].[pricing_trigger_event_type] ON 

INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (1, N'NOR', N'Notice of Readiness', N'DOCUMENTARY', N'VESSEL,BARGE', N'OIL,GAS,AGRICULTURAL,METALS', 1, 0, 0, 0, 10, N'Vessel tenders NOR at load or discharge port. Master declares vessel ready to load/discharge.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (2, N'LAYCAN_START', N'Start of Laycan Window', N'DOCUMENTARY', N'VESSEL,BARGE', N'OIL,GAS,AGRICULTURAL,METALS', 0, 0, 0, 0, 20, N'Start of the agreed laycan (laydays cancelling) window. Vessel must arrive within this window.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (3, N'COL', N'Commencement of Loading', N'DOCUMENTARY', N'VESSEL,BARGE', N'OIL,GAS,AGRICULTURAL,METALS', 1, 0, 0, 0, 30, N'First molecule/unit flows into vessel at load port. Time logged by terminal.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (4, N'EOL', N'End of Loading', N'DOCUMENTARY', N'VESSEL,BARGE', N'OIL,GAS,AGRICULTURAL,METALS', 1, 0, 0, 0, 40, N'Last molecule/unit loaded. Hoses disconnected. Used for laytime calculation.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (5, N'BL', N'Bill of Lading Date', N'DOCUMENTARY', N'VESSEL,BARGE', N'OIL,GAS,AGRICULTURAL,METALS', 1, 0, 0, 0, 50, N'Date on the Bill of Lading. Title transfer date for FOB cargoes. Most common oil pricing trigger.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (6, N'COD', N'Commencement of Discharge', N'DOCUMENTARY', N'VESSEL,BARGE', N'OIL,GAS,AGRICULTURAL,METALS', 1, 0, 0, 1, 80, N'First molecule/unit flows out of vessel at discharge port. Common CIF/DES pricing trigger.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (7, N'EOD_DISCHARGE', N'End of Discharge', N'DOCUMENTARY', N'VESSEL,BARGE', N'OIL,GAS,AGRICULTURAL,METALS', 1, 0, 0, 1, 90, N'Last molecule/unit discharged. Hoses disconnected at discharge port.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (8, N'OUTTURN', N'Outturn / Final Measurement', N'INSPECTION', NULL, N'OIL,METALS,AGRICULTURAL', 1, 0, 0, 2, 100, N'Final independent measurement of quantity and quality after discharge. Used for metals warrant outturn and tank outturn.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (9, N'PIPELINE_ENTRY', N'Pipeline Entry / Injection', N'DOCUMENTARY', N'PIPELINE', N'OIL,GAS', 1, 0, 0, 0, 30, N'Commodity injected into pipeline at entry point. Title may transfer here for pipeline trades.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (10, N'PIPELINE_EXIT', N'Pipeline Exit / Offtake', N'DOCUMENTARY', N'PIPELINE', N'OIL,GAS', 1, 0, 0, 0, 80, N'Commodity offtaken from pipeline at exit point.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (11, N'TRUCK_LOADING', N'Truck Loading Complete', N'DOCUMENTARY', N'TRUCK', N'OIL,AGRICULTURAL', 1, 0, 0, 0, 40, N'Truck tanker or dry bulk truck loading confirmed complete at terminal/facility.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (12, N'TRUCK_DELIVERY', N'Truck Delivery Confirmed', N'DOCUMENTARY', N'TRUCK', N'OIL,AGRICULTURAL', 1, 0, 0, 0, 80, N'Delivery confirmed at buyer premises by signed delivery note.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (13, N'RAIL_DEPARTURE', N'Railcar Departure', N'DOCUMENTARY', N'RAILCAR', N'OIL,AGRICULTURAL,METALS', 1, 0, 0, 0, 40, N'Railcar/consist departs origin siding. Waybill issued.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (14, N'RAIL_ARRIVAL', N'Railcar Arrival', N'DOCUMENTARY', N'RAILCAR', N'OIL,AGRICULTURAL,METALS', 1, 0, 0, 1, 80, N'Railcar/consist arrives at destination siding.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (15, N'DEEMED_BL', N'Deemed Bill of Lading Date', N'DEEMED', N'VESSEL,BARGE', N'OIL,GAS,AGRICULTURAL,METALS', 0, 1, 0, 0, NULL, N'Contractual fallback date used when actual BL is not received by deadline. Date agreed in contract (e.g. mid-month, or estimated loading date).', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (16, N'DEEMED_ARRIVAL', N'Deemed Arrival Date', N'DEEMED', N'VESSEL,BARGE', N'OIL,GAS', 0, 1, 0, 0, NULL, N'Fallback arrival date used when NOR not tendered within agreed window.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (17, N'DEEMED_DELIVERY', N'Deemed Delivery Date', N'DEEMED', NULL, NULL, 0, 1, 0, 0, NULL, N'Contractual fallback delivery date. Used across all MOT types when actual delivery date cannot be confirmed in time.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (18, N'CONTRACTUAL_DATE', N'Contractual Fixed Date', N'DEEMED', NULL, NULL, 0, 1, 0, 0, NULL, N'A specific date explicitly stated in the contract. Does not depend on any physical event.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (19, N'ACTUAL_DATE', N'Actual Agreed Date', N'TIME_BASED', NULL, NULL, 0, 0, 0, 0, NULL, N'A specific calendar date agreed between buyer and seller at trade time. Most common for financial/paper trades.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (20, N'PRICING_PERIOD_START', N'Start of Pricing Period', N'TIME_BASED', NULL, NULL, 0, 0, 1, 0, NULL, N'First day of the agreed pricing period. System-generated from delivery period.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (21, N'PRICING_PERIOD_END', N'End of Pricing Period', N'TIME_BASED', NULL, NULL, 0, 0, 1, 0, NULL, N'Last day of the agreed pricing period. System-generated from delivery period.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (22, N'DELIVERY_MONTH_START', N'First Day of Delivery Month', N'TIME_BASED', NULL, NULL, 0, 0, 1, 0, NULL, N'First calendar day of the delivery month. Used for monthly average pricing.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (23, N'DELIVERY_MONTH_END', N'Last Day of Delivery Month', N'TIME_BASED', NULL, NULL, 0, 0, 1, 0, NULL, N'Last calendar day of the delivery month.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (24, N'EXPIRY_DATE', N'Contract Expiry Date', N'EXCHANGE', NULL, NULL, 0, 0, 1, 0, NULL, N'Exchange contract expiry date. From market_product_period.expiry_date. Used for exchange-traded futures/options.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (25, N'FIXING_DATE', N'Official Price Fixing Date', N'EXCHANGE', NULL, N'METALS', 0, 0, 1, 0, NULL, N'Official exchange price fixing date. LME: official cash settlement price. Used for metals pricing.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (26, N'LME_CASH', N'LME Cash / Prompt Date', N'EXCHANGE', NULL, N'METALS', 0, 0, 1, 0, NULL, N'LME cash price — two business days forward from trade date. Standard for LME base metals.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (27, N'LME_3MONTH', N'LME 3-Month Price', N'EXCHANGE', NULL, N'METALS', 0, 0, 1, 0, NULL, N'LME 3-month forward price. Used for LME hedging and some physical trades.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (28, N'PUBLICATION_DATE', N'Index Publication Date', N'EXCHANGE', NULL, NULL, 0, 0, 1, 0, NULL, N'Date the price index is officially published. Used for financial gas/power trades and paper oil.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (29, N'INVOICE_DATE', N'Invoice Issue Date', N'SETTLEMENT', NULL, NULL, 0, 0, 0, 0, NULL, N'Date the invoice is issued. Rarely used as pricing trigger but exists in some legacy contracts.', 1)
INSERT [dbo].[pricing_trigger_event_type] ([trigger_type_id], [trigger_code], [trigger_name], [trigger_category], [applicable_mot_codes], [applicable_commodities], [requires_physical_confirmation], [is_fallback_type], [is_system_generated], [typical_confirmation_days], [lifecycle_sequence], [description], [is_active]) VALUES (30, N'INSPECTION_DATE', N'Independent Inspection Date', N'INSPECTION', NULL, N'AGRICULTURAL,METALS', 1, 0, 0, 1, NULL, N'Date of independent quality/quantity inspection. Used in agricultural and metals trades where quality determines final price.', 1)
SET IDENTITY_INSERT [dbo].[pricing_trigger_event_type] OFF

SET IDENTITY_INSERT [dbo].[screen_field_registry] ON 

INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (1, N'TRADE_BLOTTER', N'tradeDate', N'Trade Date', N'Core Trade', 1, 10, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (2, N'TRADE_BLOTTER', N'executionDatetime', N'Execution Date/Time', N'Core Trade', 0, 20, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (3, N'TRADE_BLOTTER', N'commodityType', N'Commodity Type', N'Core Trade', 1, 30, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (4, N'TRADE_BLOTTER', N'tradeType', N'Trade Type', N'Core Trade', 1, 40, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (5, N'TRADE_BLOTTER', N'direction', N'Direction (Buy/Sell)', N'Core Trade', 1, 50, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (6, N'TRADE_BLOTTER', N'status', N'Trade Status', N'Core Trade', 1, 60, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (7, N'TRADE_BLOTTER', N'notes', N'Notes', N'Core Trade', 0, 70, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (8, N'TRADE_BLOTTER', N'counterpartyId', N'Counterparty', N'Counterparty & Book', 1, 80, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (9, N'TRADE_BLOTTER', N'traderId', N'Trader', N'Counterparty & Book', 1, 90, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (10, N'TRADE_BLOTTER', N'bookId', N'Book', N'Counterparty & Book', 1, 100, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (11, N'TRADE_BLOTTER', N'legalEntityId', N'Legal Entity', N'Counterparty & Book', 1, 110, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (12, N'TRADE_BLOTTER', N'productId', N'Product', N'Product & Market', 0, 120, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (13, N'TRADE_BLOTTER', N'marketId', N'Market', N'Product & Market', 0, 130, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (14, N'TRADE_BLOTTER', N'pricingRuleId', N'Pricing Rule', N'Product & Market', 0, 140, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (15, N'TRADE_BLOTTER', N'periodCode', N'Delivery Period', N'Product & Market', 0, 150, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (16, N'TRADE_BLOTTER', N'quantity', N'Quantity', N'Quantity & Price', 1, 160, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (17, N'TRADE_BLOTTER', N'uomCode', N'Unit of Measure', N'Quantity & Price', 1, 170, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (18, N'TRADE_BLOTTER', N'price', N'Price', N'Quantity & Price', 1, 180, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (19, N'TRADE_BLOTTER', N'currencyCode', N'Currency', N'Quantity & Price', 1, 190, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (20, N'TRADE_BLOTTER', N'settlementType', N'Settlement Type', N'Quantity & Price', 1, 200, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (21, N'TRADE_BLOTTER', N'incotermCode', N'Incoterm', N'Logistics', 0, 210, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (22, N'TRADE_BLOTTER', N'deliveryLocationCode', N'Delivery Location', N'Logistics', 0, 220, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (23, N'TRADE_BLOTTER', N'oilDetail.crudeGrade', N'Crude Grade', N'Oil Details', 0, 300, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (24, N'TRADE_BLOTTER', N'oilDetail.apiGravity', N'API Gravity', N'Oil Details', 0, 310, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (25, N'TRADE_BLOTTER', N'oilDetail.sulphurPct', N'Sulphur %', N'Oil Details', 0, 320, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (26, N'TRADE_BLOTTER', N'oilDetail.loadLocationCode', N'Load Port', N'Oil Details', 0, 330, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (27, N'TRADE_BLOTTER', N'oilDetail.dischargeLocationCode', N'Discharge Port', N'Oil Details', 0, 340, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (28, N'TRADE_BLOTTER', N'oilDetail.vesselName', N'Vessel', N'Oil Details', 0, 350, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (29, N'TRADE_BLOTTER', N'oilDetail.laycanStart', N'Laycan Start', N'Oil Details', 0, 360, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (30, N'TRADE_BLOTTER', N'oilDetail.laycanEnd', N'Laycan End', N'Oil Details', 0, 370, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (31, N'TRADE_BLOTTER', N'oilDetail.blDate', N'B/L Date', N'Oil Details', 0, 380, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (32, N'TRADE_BLOTTER', N'oilDetail.norsTenderedDate', N'NOR Tendered', N'Oil Details', 0, 390, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (33, N'TRADE_BLOTTER', N'oilDetail.codDate', N'COD Date', N'Oil Details', 0, 400, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (34, N'TRADE_BLOTTER', N'oilDetail.pipelineId', N'Pipeline', N'Oil Details', 0, 410, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (35, N'TRADE_BLOTTER', N'gasDetail.deliveryHub', N'Delivery Hub', N'Gas Details', 0, 500, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (36, N'TRADE_BLOTTER', N'gasDetail.gasDeliveryStart', N'Gas Delivery Start', N'Gas Details', 0, 510, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (37, N'TRADE_BLOTTER', N'gasDetail.gasDeliveryEnd', N'Gas Delivery End', N'Gas Details', 0, 520, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (38, N'TRADE_BLOTTER', N'gasDetail.swingPct', N'Swing %', N'Gas Details', 0, 530, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (39, N'TRADE_BLOTTER', N'gasDetail.gasDayType', N'Gas Day Type', N'Gas Details', 0, 540, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (40, N'TRADE_BLOTTER', N'gasDetail.nominationType', N'Nomination Type', N'Gas Details', 0, 550, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (41, N'TRADE_BLOTTER', N'powerDetail.loadType', N'Load Type', N'Power Details', 0, 600, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (42, N'TRADE_BLOTTER', N'powerDetail.mwCapacity', N'MW Capacity', N'Power Details', 0, 610, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (43, N'TRADE_BLOTTER', N'powerDetail.mwhVolume', N'MWh Volume', N'Power Details', 0, 620, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (44, N'TRADE_BLOTTER', N'powerDetail.gridNodeCode', N'Grid Node', N'Power Details', 0, 630, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (45, N'TRADE_BLOTTER', N'powerDetail.interconnector', N'Interconnector', N'Power Details', 0, 640, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (46, N'TRADE_BLOTTER', N'powerDetail.deliveryStart', N'Delivery Start', N'Power Details', 0, 650, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (47, N'TRADE_BLOTTER', N'powerDetail.deliveryEnd', N'Delivery End', N'Power Details', 0, 660, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (48, N'TRADE_BLOTTER', N'lngDetail.loadTerminalCode', N'Load Terminal', N'LNG Details', 0, 700, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (49, N'TRADE_BLOTTER', N'lngDetail.dischargeTerminalCode', N'Discharge Terminal', N'LNG Details', 0, 710, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (50, N'TRADE_BLOTTER', N'lngDetail.cargoVolumeMmbtu', N'Cargo Volume MMBTU', N'LNG Details', 0, 720, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (51, N'TRADE_BLOTTER', N'lngDetail.priceBasis', N'Price Basis', N'LNG Details', 0, 730, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (52, N'TRADE_BLOTTER', N'metalsDetail.metalGrade', N'Metal Grade', N'Metals Details', 0, 800, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (53, N'TRADE_BLOTTER', N'metalsDetail.shape', N'Shape', N'Metals Details', 0, 810, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (54, N'TRADE_BLOTTER', N'metalsDetail.lmeDate', N'LME Date', N'Metals Details', 0, 820, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (55, N'TRADE_BLOTTER', N'metalsDetail.warehouseLocationCode', N'Warehouse', N'Metals Details', 0, 830, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (56, N'TRADE_BLOTTER', N'metalsDetail.brand', N'Brand', N'Metals Details', 0, 840, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (57, N'TRADE_BLOTTER', N'agriDetail.cropYear', N'Crop Year', N'Agri Details', 0, 900, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (58, N'TRADE_BLOTTER', N'agriDetail.gradeQuality', N'Grade / Quality', N'Agri Details', 0, 910, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (59, N'TRADE_BLOTTER', N'agriDetail.originCountry', N'Origin Country', N'Agri Details', 0, 920, 1)
INSERT [dbo].[screen_field_registry] ([field_id], [screen_code], [field_key], [field_label], [field_group], [is_required_field], [sort_order], [is_active]) VALUES (60, N'TRADE_BLOTTER', N'agriDetail.deliveryBasis', N'Delivery Basis', N'Agri Details', 0, 930, 1)
SET IDENTITY_INSERT [dbo].[screen_field_registry] OFF

SET IDENTITY_INSERT [dbo].[pricing_window_rule] ON 

INSERT [dbo].[pricing_window_rule] ([window_rule_id], [commodity_type], [rule_code], [rule_name], [window_type], [days_before], [days_after], [day_count_type], [calendar_id], [market_id], [min_fixings_required], [missing_fixing_rule], [backup_source_id], [averaging_method], [price_rounding_dp], [description], [is_active], [created_at], [created_by]) VALUES (1, NULL, N'SINGLE_DAY', N'Single Day (Trigger Date Only)', N'SINGLE_DAY', 0, 0, N'PUBLICATION', NULL, NULL, 1, N'PRIOR_DAY', NULL, N'SIMPLE', 2, N'Price = index fixing on trigger date only. No averaging.', 1, CAST(N'2026-07-12T11:19:44.2557408' AS DateTime2), N'SYSTEM')
INSERT [dbo].[pricing_window_rule] ([window_rule_id], [commodity_type], [rule_code], [rule_name], [window_type], [days_before], [days_after], [day_count_type], [calendar_id], [market_id], [min_fixings_required], [missing_fixing_rule], [backup_source_id], [averaging_method], [price_rounding_dp], [description], [is_active], [created_at], [created_by]) VALUES (2, N'OIL', N'3DAY_SYMMETRIC', N'3-Day Symmetric (BL -1/0/+1)', N'SYMMETRIC', 1, 1, N'PUBLICATION', NULL, NULL, 2, N'PRIOR_DAY', NULL, N'SIMPLE', 2, N'Average of: day before, trigger day, day after. Most common for Dated Brent FOB.', 1, CAST(N'2026-07-12T11:19:44.2557408' AS DateTime2), N'SYSTEM')
INSERT [dbo].[pricing_window_rule] ([window_rule_id], [commodity_type], [rule_code], [rule_name], [window_type], [days_before], [days_after], [day_count_type], [calendar_id], [market_id], [min_fixings_required], [missing_fixing_rule], [backup_source_id], [averaging_method], [price_rounding_dp], [description], [is_active], [created_at], [created_by]) VALUES (3, N'OIL', N'5DAY_SYMMETRIC', N'5-Day Symmetric (-2/0/+2)', N'SYMMETRIC', 2, 2, N'PUBLICATION', NULL, NULL, 3, N'PRIOR_DAY', NULL, N'SIMPLE', 2, N'Average over 5-day window centred on trigger date.', 1, CAST(N'2026-07-12T11:19:44.2557408' AS DateTime2), N'SYSTEM')
INSERT [dbo].[pricing_window_rule] ([window_rule_id], [commodity_type], [rule_code], [rule_name], [window_type], [days_before], [days_after], [day_count_type], [calendar_id], [market_id], [min_fixings_required], [missing_fixing_rule], [backup_source_id], [averaging_method], [price_rounding_dp], [description], [is_active], [created_at], [created_by]) VALUES (4, N'OIL', N'5DAY_FORWARD_COD', N'5-Day Forward from COD', N'FORWARD', 0, 4, N'PUBLICATION', NULL, NULL, 3, N'PRIOR_DAY', NULL, N'SIMPLE', 2, N'Average of COD date through COD+4. Common for CIF discharge pricing.', 1, CAST(N'2026-07-12T11:19:44.2557408' AS DateTime2), N'SYSTEM')
INSERT [dbo].[pricing_window_rule] ([window_rule_id], [commodity_type], [rule_code], [rule_name], [window_type], [days_before], [days_after], [day_count_type], [calendar_id], [market_id], [min_fixings_required], [missing_fixing_rule], [backup_source_id], [averaging_method], [price_rounding_dp], [description], [is_active], [created_at], [created_by]) VALUES (5, N'OIL', N'3DAY_FORWARD_NOR', N'3-Day Forward from NOR', N'FORWARD', 0, 2, N'PUBLICATION', NULL, NULL, 2, N'PRIOR_DAY', NULL, N'SIMPLE', 2, N'Average of NOR date through NOR+2.', 1, CAST(N'2026-07-12T11:19:44.2557408' AS DateTime2), N'SYSTEM')
INSERT [dbo].[pricing_window_rule] ([window_rule_id], [commodity_type], [rule_code], [rule_name], [window_type], [days_before], [days_after], [day_count_type], [calendar_id], [market_id], [min_fixings_required], [missing_fixing_rule], [backup_source_id], [averaging_method], [price_rounding_dp], [description], [is_active], [created_at], [created_by]) VALUES (6, N'OIL', N'5DAY_BACKWARD_BL', N'5-Day Backward to BL (-4/0)', N'BACKWARD', 4, 0, N'PUBLICATION', NULL, NULL, 3, N'PRIOR_DAY', NULL, N'SIMPLE', 2, N'Average of 4 days before BL through BL date.', 1, CAST(N'2026-07-12T11:19:44.2557408' AS DateTime2), N'SYSTEM')
INSERT [dbo].[pricing_window_rule] ([window_rule_id], [commodity_type], [rule_code], [rule_name], [window_type], [days_before], [days_after], [day_count_type], [calendar_id], [market_id], [min_fixings_required], [missing_fixing_rule], [backup_source_id], [averaging_method], [price_rounding_dp], [description], [is_active], [created_at], [created_by]) VALUES (7, NULL, N'MONTHLY_AVG_ALL', N'Monthly Average — All Publication Days', N'DELIVERY_MONTH', 0, 0, N'PUBLICATION', NULL, NULL, 15, N'EXCLUDE', NULL, N'SIMPLE', 2, N'Average of all index publication days in delivery month. Standard for monthly gas/power.', 1, CAST(N'2026-07-12T11:19:44.2557408' AS DateTime2), N'SYSTEM')
INSERT [dbo].[pricing_window_rule] ([window_rule_id], [commodity_type], [rule_code], [rule_name], [window_type], [days_before], [days_after], [day_count_type], [calendar_id], [market_id], [min_fixings_required], [missing_fixing_rule], [backup_source_id], [averaging_method], [price_rounding_dp], [description], [is_active], [created_at], [created_by]) VALUES (8, N'GAS', N'GAS_MONTHLY_BIZ', N'Gas Monthly Average — Business Days', N'DELIVERY_MONTH', 0, 0, N'BUSINESS', NULL, NULL, 15, N'PRIOR_DAY', NULL, N'SIMPLE', 3, N'Average of all business days in gas delivery month. NBP/TTF standard.', 1, CAST(N'2026-07-12T11:19:44.2557408' AS DateTime2), N'SYSTEM')
INSERT [dbo].[pricing_window_rule] ([window_rule_id], [commodity_type], [rule_code], [rule_name], [window_type], [days_before], [days_after], [day_count_type], [calendar_id], [market_id], [min_fixings_required], [missing_fixing_rule], [backup_source_id], [averaging_method], [price_rounding_dp], [description], [is_active], [created_at], [created_by]) VALUES (9, N'POWER', N'POWER_MONTHLY_PEAK', N'Power Monthly Average — Peak Hours', N'DELIVERY_MONTH', 0, 0, N'TRADING', NULL, NULL, 15, N'EXCLUDE', NULL, N'SIMPLE', 2, N'Average over peak trading hours of delivery month.', 1, CAST(N'2026-07-12T11:19:44.2557408' AS DateTime2), N'SYSTEM')
INSERT [dbo].[pricing_window_rule] ([window_rule_id], [commodity_type], [rule_code], [rule_name], [window_type], [days_before], [days_after], [day_count_type], [calendar_id], [market_id], [min_fixings_required], [missing_fixing_rule], [backup_source_id], [averaging_method], [price_rounding_dp], [description], [is_active], [created_at], [created_by]) VALUES (10, N'METALS', N'LME_CASH_SINGLE', N'LME Cash Single Day Fix', N'SINGLE_DAY', 0, 0, N'TRADING', NULL, NULL, 1, N'SUSPEND', NULL, N'SIMPLE', 2, N'LME official cash price on fixing date. No averaging — single official fixing.', 1, CAST(N'2026-07-12T11:19:44.2557408' AS DateTime2), N'SYSTEM')
INSERT [dbo].[pricing_window_rule] ([window_rule_id], [commodity_type], [rule_code], [rule_name], [window_type], [days_before], [days_after], [day_count_type], [calendar_id], [market_id], [min_fixings_required], [missing_fixing_rule], [backup_source_id], [averaging_method], [price_rounding_dp], [description], [is_active], [created_at], [created_by]) VALUES (11, N'METALS', N'LME_QP_MONTHLY', N'LME Quotational Period Monthly Avg', N'DELIVERY_MONTH', 0, 0, N'TRADING', NULL, NULL, 15, N'EXCLUDE', NULL, N'SIMPLE', 2, N'Average of all LME trading days in quotational period. Standard concentrate contracts.', 1, CAST(N'2026-07-12T11:19:44.2557408' AS DateTime2), N'SYSTEM')
INSERT [dbo].[pricing_window_rule] ([window_rule_id], [commodity_type], [rule_code], [rule_name], [window_type], [days_before], [days_after], [day_count_type], [calendar_id], [market_id], [min_fixings_required], [missing_fixing_rule], [backup_source_id], [averaging_method], [price_rounding_dp], [description], [is_active], [created_at], [created_by]) VALUES (12, N'AGRICULTURAL', N'CBOT_SINGLE', N'CBOT Single Settlement Price', N'SINGLE_DAY', 0, 0, N'TRADING', NULL, NULL, 1, N'SUSPEND', NULL, N'SIMPLE', 4, N'CBOT official settlement price on expiry/notice day.', 1, CAST(N'2026-07-12T11:19:44.2557408' AS DateTime2), N'SYSTEM')
INSERT [dbo].[pricing_window_rule] ([window_rule_id], [commodity_type], [rule_code], [rule_name], [window_type], [days_before], [days_after], [day_count_type], [calendar_id], [market_id], [min_fixings_required], [missing_fixing_rule], [backup_source_id], [averaging_method], [price_rounding_dp], [description], [is_active], [created_at], [created_by]) VALUES (13, N'AGRICULTURAL', N'AGRI_5DAY_BL', N'Agricultural 5-Day Around BL', N'SYMMETRIC', 2, 2, N'TRADING', NULL, NULL, 3, N'PRIOR_DAY', NULL, N'SIMPLE', 2, N'5-day average centred on BL date. Common for grain FOB trades.', 1, CAST(N'2026-07-12T11:19:44.2557408' AS DateTime2), N'SYSTEM')
INSERT [dbo].[pricing_window_rule] ([window_rule_id], [commodity_type], [rule_code], [rule_name], [window_type], [days_before], [days_after], [day_count_type], [calendar_id], [market_id], [min_fixings_required], [missing_fixing_rule], [backup_source_id], [averaging_method], [price_rounding_dp], [description], [is_active], [created_at], [created_by]) VALUES (14, NULL, N'FULL_DELIVERY_PERIOD', N'Full Delivery Period Average', N'DELIVERY_PERIOD', 0, 0, N'PUBLICATION', NULL, NULL, 10, N'EXCLUDE', NULL, N'SIMPLE', 2, N'Average over all publication days of the full delivery period.', 1, CAST(N'2026-07-12T11:19:44.2557408' AS DateTime2), N'SYSTEM')
SET IDENTITY_INSERT [dbo].[pricing_window_rule] OFF


